### ISSUE TITLE
'edit on github' button sends to wrong url

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy-hub#102]
It sends to `https://github.com/galaxyproject/galaxy-hub/blob/master/src/Admin/GetGalaxy/index.md` instead of `https://github.com/galaxyproject/galaxy-hub/blob/master/src/admin/get-galaxy/index.md`.

Capitalization seems to be the problem.

**Comment by dannon** [comment]
Weird.  From https://new.galaxyproject.org/admin/get-galaxy/, I assume?

I actually see something even stranger, it's pointing to the wrong repo.

**Comment by dannon** [comment]
(Admin/GetGalaxy should have been wiped out, which is why the link is invalid -- I'm doublechecking the jenkins job now)

**Comment by dannon** [comment]
Looks like dannon-test-wiki emerged due to a bad merge of 2f98801e1.  Fixing that now.

**Comment by martenson** [comment]
@dannon I got there from visiting http://getgalaxy.org (which itself surprised me - that it redirects to pre-released hub) so the redirect is using capitalization. However there is probably bunch of URLs out there that use it.

**Comment by dannon** [comment]
@martenson Got it, useful info, thanks.  Three things:

1) I fixed the admin/get-galaxy/ version of the link in c217b6834c3be8b1be6dc6751f058a1894dbb2ee
2) I need to figure out why (or you can?) the jenkins rsync isn't wiping out old files.  That's not great.
3) I need to update those redirects, and we've got to come up with a good plan for doing it en masse, since we'll have thousands of rules.

**Comment by martenson** [comment]
2. rsync seems to send incremental file list, is it supposed to delete the environment before it does so?
3. yep https://github.com/galaxyproject/galaxy-hub/issues/40

**Comment by dannon** [comment]
@martenson Yeah, we want to delete anything on the destination that isn't any longer in the source.  I thought the rsync command I set up did that, but maybe not.  I can look into it.

I don't want to delete everything first, because then during the copy people would all get 404's.

**Comment by martenson** [comment]
maybe one or both of these rsync flags?
```
--delete                delete extraneous files from dest dirs
--delete-after          receiver deletes after transfer, not before
```

**Comment by dannon** [comment]
Let me try that and rerun jenkins.

**Comment by dannon** [comment]
@martenson --delete was the magic, perfect.

Now I just need to fix that redirect and I'll close this out.

**Comment by dannon** [comment]
Fixed getgalaxy.org.  Following up on more redirects in #40
