### ISSUE TITLE
make watch does not work for styles

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy-hub#105]
In spite of detecting the changes, not sure if the error is related.

```
serving /Users/marten/devel/git/galaxy-hub/build at http://0.0.0.0:8080
[metalsmith-watch] ✔︎ Watching src/**/*
[metalsmith-watch] ✔︎ Watching layouts/**/*
Done
[metalsmith-watch] ✔︎ src/css/styles.less changed
[metalsmith-watch] - Updating 1 file...
[metalsmith-watch] ✗ Error: file "config/menu.yaml" not found
```

**Comment by dannon** [comment]
I've been fighting with ```make watch``` ever since I added it.  It just doesn't work well at all with metadata collections, styles, and a bunch of other things.  I had high hopes, but now that the build process is way faster, I'm just going to remove it.

**Comment by martenson** [comment]
@dannon `faster` - I cannot comment on, but `fast` it definitely is not :) It takes ~1m on my box which is superlong for static page dev.

**Comment by dannon** [comment]
Wow, we need to upgrade your toaster.  I'm looking at ~18s.

**Comment by dannon** [comment]
Removed in 4567977abe2bade8a477b71e38b6b2f7cca9ebf6.  We can always add it back if you figure out a way to actually make it work -- there might be another library we could/should be using.
