### ISSUE TITLE
Missing mailing list button in the mainpage

### ISSUE THREAD

**Issue by mariipia10** [galaxyproject/galaxy-hub#1072]
I wanted to see if Galaxy had any mailing list related to news and events but I didn't find them searching in the Galaxy community hub

I've searched within the menues but didn't find it,  but then did so in usegalaxy.org >Help > Mailing list 
![image](https://user-images.githubusercontent.com/92181987/145305809-77925c12-3eb1-4951-afba-834cc507e559.png)

I think adding a "Join our mailing list" button in the mainpage would make it easier for people to find it and subscribe.

Also maybe adding it in one of the dropdowns menues would be useful (Community, for e.g.)

**Comment by NickSto** [comment]
If there's consensus, I'll add the same "Mailing Lists" link under the "Community" NavBar dropdown.

**Comment by beatrizserrano** [comment]
It's now added under "About" so I'll close this, thanks @mariipia10 for pointing this out!
