### ISSUE TITLE
Redirects don't seem to be working

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy-hub#1077]
https://galaxyproject.org/tutorials/rb-rnaseq/ has a redirect box which is expected but doesn't seem to include the META redirect header and I don't *think* I'm blocking any js?

**Comment by dannon** [comment]
Anything in the dev console?  The redirect works for me (though as in the info box, it only kicks off after 5 seconds)

**Comment by hexylena** [comment]
:woman_shrugging: it worked the second time, maybe some js failed to fire, who knows.

**Comment by hexylena** [comment]
thanks @dannon !

**Comment by dannon** [comment]
@hexylena No worries!
