### ISSUE TITLE
conversion from wiki seems to have failed for some pages due to high rate of requests

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy-hub#108]
example here: https://github.com/galaxyproject/galaxy-hub/blob/master/src/learn/datatypes/index.md

Seems to affect around ~~40 markdown files~~ 20 pages. List:

https://gist.github.com/martenson/0ed08b7d7924ac04252510e0a03e2932

**Comment by dannon** [comment]
There's an open issue for this here:  #99.

Many of these were redirect pages that we were intentionally letting die.  Basically anything that's a FileName.md instead of FileName/index.md is in error.
