### ISSUE TITLE
Hook up unified search

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy-hub#11]
@tnabtaf Want to take this one?

The search field is in the mastheads, just needs to be linked up to the custom search.

**Comment by tnabtaf** [comment]
Um, Yeah!

I'm on it, or will be sometime this week.

**Comment by tnabtaf** [comment]
Hmm. Can't seem to assign myself to it.

**Comment by tnabtaf** [comment]
Just saw this mentioned in Gitter, which reminds me...

We have custom Google searches set up for Galaxy (never name your project with a common word, by the way).  Here's what I'm thinking for the search box.

Have it use a Google custom search that somehow favors results from the hub, but also shows, or makes it easy to get to, results from all Galaxy sites.  My memory is that this sort of thing is doable.

**Comment by dannon** [comment]
Yes, exactly, I was thinking the box built into the masthead would become the "one true search box", instead of having to find galaxyproject.org/search or wahtever.

**Comment by tnabtaf** [comment]
I like it!

**Comment by tnabtaf** [comment]
@dannon and I are looking into dropping all searches except for the one true search that searches everything, and segments the material using Google Custom search tabs (known as "Refinements" in Google speak.

This is potentially something that could affect lots of Galaxy products, not just the hub.  Any suggestions on where to post an issue that covers this?  

I can certainly create a separate issue (or rename this one) for the hub changes.

**Comment by tnabtaf** [comment]
Within the hub, all links are now to the unified unified search.  Looking elsewhere now.

**Comment by tnabtaf** [comment]
All links on lists.galaxyproject.org updated.

**Comment by tnabtaf** [comment]
All links of Nabble archives updated.

**Comment by dannon** [comment]
Forwarded galaxyproject.org/search* to the new URLs, and I hooked up the unified search in #169.  Closing this issue and moving on.
