### ISSUE TITLE
Page Not Found: https://galaxyproject.org/tutorials/collections/

### ISSUE THREAD

**Issue by loraine-gueguen** [galaxyproject/galaxy-hub#1116]
The page https://galaxyproject.org/tutorials/collections/ is redirected to https://galaxyproject.org/learn/, but the content is lost, I can't find it anywhere on https://galaxyproject.org. The page was still available last tuesday.

Unfortunately, the tutorial https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/collections/tutorial.html is not suitable for me because it is too much sequence oriented (with paired datasets)

Is it possible to recover the content of https://galaxyproject.org/tutorials/collections/ somewhere ?

Of course it would be better to build a tutorial with that, but I am too short in time before the training... 

Thanks in advance !

**Comment by hexylena** [comment]
Hi @loraine-gueguen, we're in the process of cleaning out some of the very outdated content. If you need to access the old site, I can recommend using wayback machine: https://web.archive.org/web/20210320075157/https://galaxyproject.org/tutorials/collections/ there the tutorial is visible.

I'm surprised you say the gtn is too sequencing oriented, my impression is the tutorials/collections resource is entirely focused on paired-end fastq datasets.

Hopefully we can come up with a good, general tutorial in the future. We'd love to hear a bit about your non-sequencing use case so we can write something general :)

**Comment by loraine-gueguen** [comment]
Hi @hexylena,I was a little upset because the content was gone...
I want to say that the GTN resources are great and very very helpful. In fact, this year I chose to use them (slides and tutorials) as much as possible in the one-day training I'm doing on the introduction to Galaxy. It is a training that is meant to be as agnostic as possible, even if there are some examples with sequence data, because the audience can come from other fields (metabolomics...). So I don't intend to talk about paired sequences. And I had "exhumed" this tutorial on galaxyproject.org which suited me well (creation and management of a simple list of datasets). But I fully understand the need to clean up: it is up to me to contribute to the GTN to add this more generic use case :-)
Thanks again for this awesome work!

**Comment by nekrut** [comment]
@loraine-gueguen -> the collection description was moved to this tutorial -> https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/collections/tutorial.html
