### ISSUE TITLE
Community link in top menu does not work

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy-hub#114]
On both Firefox and Chrome, the "Community" link in the top menu points to '#' instead of https://new.galaxyproject.org/community/ . The problem seems to be in `src/config/menu.yaml` , but I don't know how to fix it.

**Comment by dannon** [comment]
I'll check it out.

**Comment by dannon** [comment]
@nsoranzo The source in ```src/config/menu.yaml``` is correct, we're just not rendering a non-list entry well.  I'll fix it.

**Comment by dannon** [comment]
Should be fixed with 32de9ae324aefdf3c6222563fd2b24454d8a2cbc and 3674ad5b19522ddd6b5d3367adb6782bb34a2ccb.

Thanks @nsoranzo
