### ISSUE TITLE
404 for https://galaxyproject.org/tools/requirements/ 

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/galaxy-hub#1167]
Hi,

When clicking on `?` after "Requirements" (see below) in the help section for tool I was redirected on the hub (https://galaxyproject.org/tools/requirements/), a 404 page

![image](https://user-images.githubusercontent.com/1842467/151549523-6ee245df-f54b-4628-96d4-944f8296ad12.png)

**Comment by NickSto** [comment]
Where is this link? Is this in the Hub or Galaxy?

**Comment by bebatut** [comment]
In Galaxy

**Comment by NickSto** [comment]
Huh. Well apparently [this](https://web.archive.org/web/20170710051538/https://galaxyproject.org/tools/requirements/) is what used to be there. I'll try to find where it went or replace it.
