### ISSUE TITLE
Menu Clutter

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy-hub#118]
The menu just became very cluttered with #117 and #116 @nekrut @martenson.

We should narrow this down to maybe (5?) options, and we can change to a two-tiered list if necessary.

![image](https://cloud.githubusercontent.com/assets/155398/22704362/71a660ae-ed35-11e6-9330-ad3a9498af52.png)

**Comment by dannon** [comment]
How about merging "Teach" and "Learn" into "Education" or something?

And, "Community" -- should this be merged with "Pulse"?

**Comment by martenson** [comment]
+1, but I would stand by for a bit and watch what crystalizes out and cleanup afterwards since both me and @nekrut are working on hub currently.

**Comment by dannon** [comment]
You two aren't the only ones :)

But, yeah, higher-level things like this (the menu), we probably want to have an Issue (or open PR for a bit) for discussion prior to merging in changes.

**Comment by martenson** [comment]
I assumed you know about your intents better than myself so I did not mention you. No offense.

**Comment by dannon** [comment]
@martenson Sorry, there wasn't any taken, I was just saying there's a lot going on right now and I hope even more people jump in and start editing.

**Comment by martenson** [comment]
As a side note I think top menu links should not have target outside of the page. If it is important enough to have a link there, it should have at least an 'about' page on the hub.

**Comment by dannon** [comment]
Trimmed this down slightly when I added the search.  We can always edit it, but I'm trying to prune down issues that aren't actionable right now.
