### ISSUE TITLE
Tables of Contents are unclickable on mobile

### ISSUE THREAD

**Issue by NickSto** [galaxyproject/galaxy-hub#1215]

**Comment by ManaliPawar** [comment]
hello, this is Manali, an outreachy applicant currently studying in IIT BHU and proficient in HTML, CSS, JS. Can I work on this issue?

**Comment by NickSto** [comment]
@ManaliPawar Hi! Sure that'd be great! I haven't had a chance to dig into it yet.

**Comment by ManaliPawar** [comment]
could you please help regarding how to set up the environment on a laptop?

**Comment by ManaliPawar** [comment]
@beatrizserrano @NickSto

**Comment by dannon** [comment]
@ManaliPawar Check out the readme here (https://github.com/galaxyproject/galaxy-hub#getting-started), it should have good instructions for getting started.  If you run into any trouble, though, let us know in detail what's going wrong and maybe we can improve it.
