### ISSUE TITLE
Move FAQs from the Hub to the GTN

### ISSUE THREAD

**Issue by garimavs** [galaxyproject/galaxy-hub#1257]
**This issue contains all the possible FAQs that can be moved from the Galaxy Community Hub to the GTN.**

1. _FAQs related to Dataset and Histories_

- [Dataset icons and their role](https://galaxyproject.org/support/dataset-icons/).
- [Different dataset status](https://galaxyproject.org/support/how-jobs-execute/).
- [Moving Dataset and Histories](https://genomicsvirtuallab.wordpress.com/2016/07/13/moving-data-between-galaxy-instances/).

2.  _FAQs related to Tools_
-  [Finding Tools](https://galaxyproject.org/support/finding-tools/) to be merged/edited with [If a Tool is missing](https://training.galaxyproject.org/training-material/faqs/galaxy/tools_missing.html).
- [Help! The tool I'm using doesn't recognize any input datasets ](https://galaxyproject.org/support/datatypes-and-tools/#help-the-tool-im-using-doesnt-recognize-any-input-datasets).

3. _Other FAQs_

- [Determining job failure types](https://galaxyproject.org/support/tool-error/#determining-the-job-failure-type).
- [Issue Reporting](https://galaxyproject.org/issues/).

By- Garima Singh(garima.singh.eee20@itbhu.ac.in)

**Comment by NickSto** [comment]
Hi @garimavs, welcome to the project! Thanks for gathering these FAQs.

It looks like there's already an issue for moving FAQs here: #1256

If you'd like to have an issue for all the FAQs, you might want to consolidate them into one issue.

**Comment by garimavs** [comment]
> Hi @garimavs, welcome to the project! Thanks for gathering these FAQs.
> 
> It looks like there's already an issue for moving FAQs here: #1256
> 
> If you'd like to have an issue for all the FAQs, you might want to consolidate them into one issue.

Hello @NickSto, pleased to be able to contribute. 

The issue mentioned was opened by another Outreachy applicant. I considered it prudent to open another issue to avoid any chaos, but since you have mentioned it, I would have a word with the mentors on what should be done!
Thanks for highlighting it.

**Comment by beatrizserrano** [comment]
Thanks @NickSto, that makes sense! We are collecting all of them [here](https://github.com/galaxyproject/galaxy-hub/issues/1262). Sorry for the noise and for not thinking about it before. 

@garimavs Some of the FAQs you wanted to work on were already taken, so I've added your GitHub handler in the rest of them. Please let me know if there's a mistake anywhere! Thanks

**Comment by garimavs** [comment]
> Thanks @NickSto, that makes sense! We are collecting all of them [here](https://github.com/galaxyproject/galaxy-hub/issues/1262). Sorry for the noise and for not thinking about it before.
> 
> @garimavs Some of the FAQs you wanted to work on were already taken, so I've added your GitHub handler in the rest of them. Please let me know if there's a mistake anywhere! Thanks

Thanks, @beatrizserrano, I will have a look at the requested tasks!
