### ISSUE TITLE
Move faq(How to find tools) to the GTN

### ISSUE THREAD

**Issue by bernandez** [galaxyproject/galaxy-hub#1258]
Hello, i am an outreachy applicant and would like to move this faq (How to find tools) from https://galaxyproject.org/support/finding-tools/ to the GTN.

**Comment by beatrizserrano** [comment]
@bernandez that FAQ was already taken, can you please select another one? They are all now collected [here](https://github.com/galaxyproject/galaxy-hub/issues/1262). Thanks!
