### ISSUE TITLE
Moving FAQs (How to Share and Publish Your Work) from the Hub to GTN

### ISSUE THREAD

**Issue by NdzeRegina** [galaxyproject/galaxy-hub#1259]
This covers the 3 different ways you can share your Galaxy items - histories, workflows, visualizations, and pages :

Individual users: Directly using a Galaxy account's email addresses. These must be on same server.
One or more users: Using a web link, with anyone who knows the link.
Everyone: Using a web link plus publishing into Shared Data.

**Comment by beatrizserrano** [comment]
@NdzeRegina we have collected all the FAQs into one [issue](https://github.com/galaxyproject/galaxy-hub/issues/1262), could you please indicate there which ones you'd like to work on? Thanks!
