### ISSUE TITLE
How should posts be aggregated across subsites?

### ISSUE THREAD

**Issue by NickSto** [galaxyproject/galaxy-hub#1317]
In the Hub meeting this morning we confronted an issue central to the Hub unification effort.

One of the main motivations of unification was making it easy to cross-post content across different Galaxy locations. Instead of having to create a post on .org that points to a .eu event, you can just tag the EU event with `us` and it will show up in the US feed as well.

But then should that post show up in the global, Galaxy-wide feed? What about an event in an EU subsite like Pasteur? Should all Pasteur events be listed in the EU-wide feed? In the global feed? What about aggregation in the other direction? Should the GenOuest feed list all EU events? All global events?

Theoretically it seems like the answers to all these questions should be yes: federation everywhere! Why not make everyone aware of everything? But I can imagine instances where you'd like to be able to post something to only one subsite (or a few). What if there's an event which will only be in French? There are [a](https://github.com/usegalaxy-eu/website/blob/master/_posts/2021-01-18-usegalaxy-fr-hiring.md) [few](https://github.com/usegalaxy-eu/website/blob/master/_events/2021-05-03-agrocampus-1.md) [examples](https://github.com/usegalaxy-eu/website/blob/master/_events/2021-05-03-agrocampus-2.md) which were posted only to French sites like GenOuest, Pasteur, VIB, and ELIXIR-FR/IFB. I could also imagine subsites might want to be a place to see *only* the stuff happening in that particular area, without all the noise of all the general EU/Global stuff.

Currently it seems the .eu site only propagates up: a post will appear only on the member sites which were tagged, plus the EU-wide feeds. If we kept that model, then the global Galaxy news & events feeds would list every post from everywhere. This might be okay, or it might be too much noise. Keeping strictly to the current .eu model would also mean we'd have to specifically tag every single subsite if we wanted a post to show up everywhere, since there's no "higher-level" site tags on .eu (like `global`, `eu`, or `us`).

Probably the most helpful thing is looking at some examples. I started a [spreadsheet](https://docs.google.com/spreadsheets/d/1b-9qXES45klWO3e644Ugiadkfkhx1ul7GRLOUcqXSzI/edit?usp=sharing) where we can pick out existing posts and list where they currently are listed, and then say where we think they *should* be listed. Please give your input by classifying some posts.

**Comment by bgruening** [comment]
The spreadsheet is a great idea, I filled it.

My guess is it will stay complicated and we should be explicit, for the time being, with handy shortcuts ( ifb, us, au, eu, all, global, freiburg, belgium), less magic.

Alternatively, we can have a transparent configuration option somewhere. Something along those lines:

```yaml
freiburg: [freiburg]
eu: [ifb, freiburg, belgium]
all: [ifb, freiburg, belgium, us, au]
```

So everyone can edit it and decide about the scope.

**Comment by NickSto** [comment]
Thanks for your input @bgruening!

Yeah, I like the idea of keeping it simple and explicit. So maybe for now we just have no automatic propagation. We require authors to explicitly list every place a post should appear.

FYI, my interpretation of this is the strict version: if someone just lists `eu`, then it *only* appears in the EU feed, not the Freiburg or global ones. Shorthands will help with this. For example, `all` could mean to post it on every subsite, so authors don't have to manually list them all. Shorthands will be listed in `config.json`.

**Comment by NickSto** [comment]
I realize this means that we'll have to go back and add a `subsites` key to every existing event on .org or the `/events/` list will be empty. I'm going to go ahead and add `subsites: [global, us]` to every post as a default, and we can manually change individual posts later if we want.
