### ISSUE TITLE
Add scroll for topic lists/menus?

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy-hub#135]
Examples: 

 - https://new.galaxyproject.org/tutorials/ngs/
 - https://new.galaxyproject.org/tutorials/histories/#history-panel-datasets

FABULOUS resource summaries however linked topics fall off the end of the right menu and there is no way to scroll through it. (Can only scroll through the primary page itself).

Sorry if this is captured somewhere else - checked and didn't find it - close/merge as appropriate.

**Comment by dannon** [comment]
Yeah, it's in #103, this is something I need to fix.
