### ISSUE TITLE
Automatically pull in GTN posts

### ISSUE THREAD

**Issue by NickSto** [galaxyproject/galaxy-hub#1417]
[update_gtn_posts.py](https://github.com/usegalaxy-eu/website/blob/master/update_gtn_posts.py) automatically pulls content from the GTN's [RSS feed](https://training.galaxyproject.org/training-material/feed.xml) (which tracks their [news posts](https://training.galaxyproject.org/training-material/news.html)) and adds them as new Hub posts.

We could use Gridsome's ability to pull in remote content and add it to the GraphQL database on build.

This might not be a high priority, though. It seems this hasn't successfully run since summer 2021.

**Comment by bgruening** [comment]
I guess Gridsome is a dead-end and we should instead of relying on some gridsome tech, just create post-files that are referencing GTN and linking out to external content.

@kysrpex could you maybe look at this at some point?

**Comment by hexylena** [comment]
you could probably accomplish this with the GTN RSS feed and like 30 lines of python I think (and a GHA action to run on cron/commit the results.)

**Comment by bgruening** [comment]
* [ ] Write a small Python script that reads the GTN RSS
* [ ] create automatically a new entry that uses `external` to link to an original blog post
* [ ] create automatically a PR against this galaxy-hub repo

I guess this can be tested in a local fork before we integrate it here.

**Comment by kysrpex** [comment]
Once this has been implemented, I assume it would make sense to remove [update_gtn_posts.py](https://github.com/usegalaxy-eu/website/blob/c7eb6c45511b06f764002556389b270b84d90629/update_gtn_posts.py) from [usegalaxy-eu/website](https://github.com/usegalaxy-eu/website) because it would no longer be needed?

**Comment by bgruening** [comment]
Yes! :)
