### ISSUE TITLE
Support for our Google Analytics flavor is going away

### ISSUE THREAD

**Issue by NickSto** [galaxyproject/galaxy-hub#1436]
[Google is moving](https://support.google.com/analytics/answer/11583528) from "Universal Analytics" to "Google Analytics 4". After July 1, 2023, it looks like the old system will no longer work.

We use Universal Analytics. [Confirmed by](https://support.google.com/analytics/answer/11583832) the fact that our property ID starts with `UA-`.

**Comment by NickSto** [comment]
One possible solution is to take this opportunity to move to [Plausible](https://plausible.io). That's what galaxyproject.eu is currently using. They're [privacy respecting](https://plausible.io/privacy-focused-web-analytics) (they don't use cookies or record IP addresses), and it would fit our values to find a way to stop serving our visitors up to the Google machine. And it looks like it still gives us enough info: visitors per page, entry pages, regions, mobile visitors, and even utm campaign data. The only catch is that it's not free. Looks like it'd be $190/year for our level of traffic.

**Comment by hexylena** [comment]
> The only catch is that it's not free. Looks like it'd be $190/year for our level of traffic.

EU hosts one! https://plausible.galaxyproject.eu/training.galaxyproject.org it would work for us :)
