### ISSUE TITLE
Move Hub documentation to ..the Hub

### ISSUE THREAD

**Issue by NickSto** [galaxyproject/galaxy-hub#1508]
Pages like [doc/AUTHORING.md](/galaxyproject/galaxy-hub/blob/master/doc/AUTHORING.md) should just be on the Hub, right?

**Comment by rajnish254** [comment]
kindly Assign me that issue
Thanks

**Comment by hexylena** [comment]
@NickSto solved this one six days ago, sorry @rajnish254

**Comment by NickSto** [comment]
Oops, forgot there was an issue for this!
