### ISSUE TITLE
Improve accessibility

### ISSUE THREAD

**Issue by NickSto** [galaxyproject/galaxy-hub#1604]
We should spend some time using tools like https://www.accessibilitychecker.org and going through different issues it uncovers.

**Comment by dannon** [comment]
Running axe directly is going to be more reliable and maintainable here -- that's what the a11y tests we have do now.  They're intentionally somewhat limited in what they enforce, though, just as a first pass.  I'm going through Galaxy right now with devtools in https://github.com/galaxyproject/galaxy/pull/14481, and will do the same here.
