### ISSUE TITLE
Unified Galaxy Search: Unify it?

### ISSUE THREAD

**Issue by tnabtaf** [galaxyproject/galaxy-hub#165]
Several years ago we set up a series of Google custom searches to search just a specific set of web sites.  We did this because our project name is also a common word, and just doing regular search engines resulted in lots of hits for unrelated stuff.

At the time we set up several distinct custom searches.  These overlap in the sites they cover, but each has a distinct emphasis.

**We ( @dannon & @tnabtaf ) would like to propose consolidating these separate searches into a single search that everything uses.**

## Current searches.
* **[Web](https://galaxyproject.org/search/web/)**: (a.k.a. Pan-Galactic Web Search) Searches everything.
  * Currently looks at 34 different sites/paths.  
  * Current tabs are `All` `Tools` `Email & Biostar` `Doc` `Source` `code` `Shared` `Abstracts` and `Requests`. 
  * *This would remain as the only search.*

* **[Mailing List](https://galaxyproject.org/search/mailinglists/)**: Searches mailing list archives, IRC, and Galaxy BioStar.  
  * Supports tabs for `All` `Proteomics` `Biostar` `(User)` `UK` `IRC` `Dev` `Announce` and `France` (but not `training`).
  *  *I don't think this search is particularly useful.  People want answers, but they don't care about what format they were presented in.*

* **[UseGalaxy](https://galaxyproject.org/search/usegalaxy/)**: Tries to only search sites that have information that end-users would care about.
  * *I think this idea is quite useful.  Not sure how well this achieves the goal.*  
  * This could also be implemented as a tab in the Web search (might be worth a try)

* **[GetGalaxy](https://galaxyproject.org/search/getgalaxy/)**: Tries to only search sites that are about administering, developing, and tool wrapping for Galaxy.
  * *I think this idea is quite useful.  Not sure how well this achieves the goal.*  
  * This could also be implemented as a tab in the Web search (might be worth a try)

* And several other searches that are only used in really obscure places, or not at all.

## Proposed search

* **[Web](https://galaxyproject.org/search/web/)**: (a.k.a. Pan-Galactic Web Search) Searches everything.
  * Look at every site/path we care about.
  * Proposed tabs are `All` `Tools` `Discussion` `Doc` `Use`  `Admin/Dev` `Abstracts` and `Requests`. 

## Adding this to the Hub

This is covered by issue #11. 

## Plan?

To do this I suggest

1. Update the Web search to use a new tab (refinement in Google speak) list
2. Update https://galaxyproject.org/search/ so it is the same as the Web search, instead of a list of links to searches.
3. Track down all links to any searches, update the linking text, and the link to go to https://galaxyproject.org/search/
   - Links could be anywhere in any Galaxy product (not just in the Hub)
4. Redirect the other https://galaxyproject.org/search/* pages to point to https://galaxyproject.org/search/
5. Drop the other custom searches from Google.

(I'm not particularly attached to the plan or the URLs as long as the old ones redirect.)

**Comment by tnabtaf** [comment]
All the search links broke when we made the hub live yesterday.  @dannon is working on getting a search page set up in the hub (galaxyproject.org/search ?) that will use the pan-Galactic search.

I'll move forward with updating the tabs / refinements on the pan-galactic search while he does that.

**Comment by tnabtaf** [comment]
I updated the pan-galactic search.  Tabs/refinements are now

- All results
- Tools 
- Discussion 
- Source code
- Shared 
- Use 
- Admin/Dev 
- Abstracts 
- Requests

That's not the order I want them in.  Trying [this next](https://productforums.google.com/forum/#!topic/customsearch/6oTSo8O_fN4) to get them in a better order.

**Comment by dannon** [comment]
#169 is a work-in-progress implementation of the search integration.

**Comment by tnabtaf** [comment]
Tabs/refinements are now

- All results
- Use 
- Admin/Dev 
- Discussion 
- Shared 
- Tools 
- Abstracts 
- Requests
- Source code

**Comment by dannon** [comment]
ok, #169 Is ready to go.

**Comment by bgruening** [comment]
Thanks a lot @tnabtaf @dannon !
