### ISSUE TITLE
Add a license for Galaxy-Hub

### ISSUE THREAD

**Issue by logankilpatrick** [galaxyproject/galaxy-hub#1664]
Hey folks! I noticed that this repo does not have a top-level license. Would it be possible to add an OSI approved one?

**Comment by bgruening** [comment]
Yes, good point. We use MIT for most of our projects, so we should make this explicit here as well.

Thanks!

**Comment by dannon** [comment]
Does MIT make sense for all the content, or is something like CC more appropriate there?

**Comment by fubar2** [comment]
Oddly enough, AFAIK, CC is not OSI approved - apparently because it's not intended for source code!

In the long run, an OSI approved license might be a better long term strategic choice?

**Comment by dannon** [comment]
Totally agreed on simply using MIT for the platform code -- what I was trying to tease out is whether or not we need to have two separate licenses.  One for the platform (the javascript, vue, etc.), and one for the non-sourcecode markdown content in `content`?

If it's appropriate to say the content in `content` is MIT licensed, then I'm happy to keep it simple!

**Comment by fubar2** [comment]
Decision boils down to whether the minor complication of a separate (non-OSI-approved!) license for marked up text and images is a good strategic choice. Worth some complexity if it make things easier for contributors and more useful for users going forward?

Suggestion: maybe start with MIT for the code, and defer a decision on the rest until contributors have had an opportunity to express their views?

**Comment by hexylena** [comment]
Maybe look at the GTN as prior art here :) 

> The content of the tutorials and website are licensed under the [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0).
>
> The code behind the infrastructure is licensed under the [MIT License](https://github.com/galaxyproject/training-material/blob/main/LICENSE.md)

**Comment by fubar2** [comment]
Thanks for confirming @dannon's solution @hexylena. Sounds perfect to me.

**Comment by dannon** [comment]
Thanks for the discussion and pointers to GTN's license configuration -- I've opened #1680 which I'll leave in draft for a while for feedback or any other clarification.

**Comment by fubar2** [comment]
Thanks for merging @dannon 
That makes this issue completed AFAIK - time to close?

**Comment by dannon** [comment]
Yep, thanks everyone!
