### ISSUE TITLE
Add Gitter link to https://botbot.me/ archive

### ISSUE THREAD

**Issue by tnabtaf** [galaxyproject/galaxy-hub#168]
This
  https://botbot.me/freenode/galaxyproject/

is a public archive of the galaxyproject IRC / Slack / Gitter channel (they are all synched).  As such it's a great URL to include in Galaxy search.  However, users can't contribute to the discussion through botbot.

Is it possible to add a link to botbot that points to the Gitter channel (https://gitter.im/galaxyproject/Lobby)?  For example, something like

- [Join the discussion](https://gitter.im/galaxyproject/Lobby)

Including Gitter or Slack in the unified search does not appear to be an option.  Google doesn't index either of them.

**Comment by dannon** [comment]
I don't see a good way to do this -- we don't really control botbot.

**Comment by tnabtaf** [comment]
@dannon.  Thanks for checking.  Closing.
