### ISSUE TITLE
403 instead of 404 when index.md is missing

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy-hub#170]
Trying to load https://galaxyproject.org/admin/tools/  you will get 403-forbidden. This is probably due to https://github.com/galaxyproject/galaxy-hub/tree/master/src/admin/tools missing `index.md`. 

I think it should give 404 instead.

**Comment by dannon** [comment]
Yep, exactly why it's erroring.  We need 
1) an index.md there, and 
2)  https://github.com/galaxyproject/galaxy-hub/blob/master/src/page-not-found/index.md was made as a easily customized 404 page, we just need to use it.

**Comment by dannon** [comment]
(404 and 403 are now functional, using page-not-found)
