### ISSUE TITLE
Galactic Career Center - Link to the Bioinformatics training officer not working

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/galaxy-hub#1725]
The link to the "Bioinformatics training officer" offer is not working there: https://galaxyproject.org/careers/

 ![image](https://user-images.githubusercontent.com/1842467/200845377-2fc8ddd9-525a-4d28-a0f4-cd32e9b94120.png)

**Comment by beatrizserrano** [comment]
isn't it because the `external_url` is missing?

**Comment by bebatut** [comment]
Should it not work with internal content if no external_url?

**Comment by bebatut** [comment]
There is an internal page: https://galaxyproject.org/careers/2022-11-ufr-training/

**Comment by beatrizserrano** [comment]
Oh, I see! then maybe that should be the link in the `external_url`? I don't think I've ever created an internal page, it was always link to external resources

**Comment by dannon** [comment]
Yeah, if there's no external_url the intent is that we link to the internal one, just like we do for events, etc.  Sounds like a bug, I'll take a quick look.

**Comment by bebatut** [comment]
Thanks @dannon!

**Comment by dannon** [comment]
Thanks for reporting the bug!  :)
