### ISSUE TITLE
Add funding info for EuroScienceGateway

### ISSUE THREAD

**Issue by stain** [galaxyproject/galaxy-hub#1734]
Add to towards bottom or so of https://galaxyproject.org/projects/esg/

Something like:

> This work was funded by the European Union programme Horizon Europe [HORIZON-INFRA-2021-EOSC-01-04] under grant agreement number [101057388](https://doi.org/10.3030/101057388) and by UK Research and Innovation (UKRI) under the UK government’s Horizon Europe funding guarantee grant number [10038963](https://gtr.ukri.org/projects?ref=10038963).

**Comment by bgruening** [comment]
@ElectronicBlueberry @itisAliRH can you please try to add this, thanks.

**Comment by bgruening** [comment]
@stain please also look at https://github.com/galaxyproject/galaxy-hub/pull/1732/files

**Comment by dannon** [comment]
Looks like this was addressed in #1732
