### ISSUE TITLE
Feature Request: "Why galaxy tools" page

### ISSUE THREAD

**Issue by erasche** [galaxyproject/galaxy-hub#177]
Feature Request: A Hub / docs page somewhere where I can link people to when telling them I wish to wrap their tool for galaxy. Some page that says "here's what galaxy is, the mission, why it's awesome" and maybe even a section specifically on "why your tool should be in galaxy". Would be nice for us tool-dev people who write so many emails requesting "can you re-license your software so we can include in galaxy" to have a single page convincing them why.

**Comment by jennaj** [comment]
@erasche Is this a good base? Is a very high-level overview. Could add a section with links that go back into the hub. Just a thought. I'd like to work on this with you if want, however it is done. Lmk.
https://galaxyproject.github.io/

**Comment by martenson** [comment]
@jennaj Eric is author of that page. :)

**Comment by erasche** [comment]
Hah, I'd actually forgotten about that page. Thanks for the reminder, that sounds like a good place to put it. I'll PR there and ping you @jennaj, thanks for the offer of help!

**Comment by martenson** [comment]
@erasche I think the latest feelings about the github.io page were to incorporate it in the hub. What do you think about that?

**Comment by erasche** [comment]
I am open to being convinced otherwise, but my impression is that serve very different purposes.

https://galaxyproject.github.io is solely about the software that the team + community has developed. The hub seems to be about some deployment configuration documentation, help sections, training, community, events, and outreach. 

When it was initially proposed, it was supposed to be similar to https://netflix.github.io/, a page describing what software we've released that others might want to take advantage of.

That said, other companies (e.g. google/facebook) just redirect to pages on their own dev sites, so again, I'm open to alternatives.

**Comment by jennaj** [comment]
I had linked galaxyproject.github.io already and just now linked the Why Galaxy on the support page. 

If we want it other places (in Admin, Develop, ??) let me know or feel free to add or I just might just add in useful places anyway :)

Close this out?
