### ISSUE TITLE
Do we need breadcrumbs?

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy-hub#178]
Imagine landing [here](https://galaxyproject.org/cloud/jetstream/storage/) or [here](https://galaxyproject.org/admin/tools/add-tool-tutorial/) or even [here](https://galaxyproject.org/admin/data-integration/)

The best bet for me to learn where I am is actually reading the URL. I believe that shouldn't be the case and providing basic breadcrumbs might be beneficial here.

**Comment by dannon** [comment]
Yep, we do.  I started working on navigation improvements on monday; @tnabtaf, @afgane and I discussed a few options (including breadcrumbs) here: https://github.com/galaxyproject/galaxy-hub/issues/171 and in a followup chat.  The current plan is to have current siblings + parents (so, the hierarchy like you'd see in breadcrumbs) above the ToC on the right.  Closing this to try to deduplicate the issues tracking this.
