### ISSUE TITLE
Wrong link in galaxy-dev mailing list footer

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy-hub#181]
That's not strictly a galaxy-hub bug, but the galaxy-dev mailing list footer contains a link to https://galaxyproject.org/search/mailinglists/ , which results in a "Page Not Found". I think that:
- [x] the mailing list footer should be updated
- [x] https://galaxyproject.org/search/mailinglists/ should be redirected to https://galaxyproject.org/search/
- [x] https://galaxyproject.org/search/ just says "Welcome to the comprehensive Galaxy search interface. Results will appear below.", it should at least point the user to the search field in the top bar.

**Comment by dannon** [comment]
Thanks for noting the issues.  I added the redirect, which is live now.  I'll go ahead and add a little more info to the search page, too.  I had wanted a neat graphic or something interesting there, but just more explanatory text would work for now :)

**Comment by dannon** [comment]
Updated dev and announce mailing lists as well.  I think we're good to go here, now.
