### ISSUE TITLE
https://galaxyproject.org/ftp-upload/

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy-hub#182]
Needs a bit of help, missing images, broken links.  This is a tutorial folks use to understand FTP upload to main, so it should be prioritized.

**Comment by dannon** [comment]
Fixed this up for the most part last week and forgot to close the issue.  Could use as much an overhaul as the rest of the hub, but it's functional with parity to the old page, now.

**Comment by martenson** [comment]
revamped in https://github.com/galaxyproject/galaxy-hub/commit/6c80598e67a0c6c5706abe77d268127aab2e6368
