### ISSUE TITLE
VarScan error: index file older than data file and fail to parse certain regions 

### ISSUE THREAD

**Issue by Anna-LB-Albuquerque** [galaxyproject/galaxy-hub#1879]
Hello!
I recieved two already aligned to hg19 and filtered BAM files and wanted to proceed with Variant Calling on VarScan Somatic for comparing normal and diseased samples. I came across the following error message:

[W::hts_idx_load2] The index file is older than the data file: normal.bam.bai
[E::mpileup] fail to parse region ‘chr11_gl000202_random:’ with normal.bam

Is there something I can do to solve this problem and use these files in VarScan or should I restart the quality control and mapping with the respective FastQ files? Although there is a workflow for that on Galaxy Training, I´d rather use the BAM files because I have never mapped data before, I usually work with BAM and VCF files. Thanks in advance, any help would be most welcome!

**Comment by bgruening** [comment]
On which Galaxy server does this happen? Does a new upload of the dataset fix it?

**Comment by wm75** [comment]
answered here: https://help.galaxyproject.org/t/varscan-error-index-file-older-than-data-file-and-fail-to-parse-certain-regions/9507
