### ISSUE TITLE
smaller viewport widths are not reflected well in the menu responsiveness

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy-hub#188]
https://galaxyproject.org/admin/

May be a known. Several pages are this way - including the side menus

**Comment by martenson** [comment]
@jennaj can you please provide a screenshot of what you mean?

**Comment by jennaj** [comment]
Looks fixed now this morning, so all good. If I run into it again will reopen.

**Comment by dannon** [comment]
Hrmm.  Nothing should have changed with the layouts, definitely take a screenshot if you see it again.  Thanks!

**Comment by jennaj** [comment]
Found it. The masthead's search box wraps down even with a wide screen view. This makes the masthead cut off the text of the active page/toc. Going to a smaller window eventually scales down the size of the masthead - that view is OK.

Problem - large window

<img width="1085" alt="screen shot 2017-03-21 at 12 48 02 pm" src="https://cloud.githubusercontent.com/assets/8999735/24167741/1a4012f8-0e35-11e7-9533-bf51f7b14e72.png">

Problem - medium window

<img width="722" alt="screen shot 2017-03-21 at 12 47 32 pm" src="https://cloud.githubusercontent.com/assets/8999735/24167752/24aad2dc-0e35-11e7-9604-f3b2f2466a3f.png">

OK - small window

<img width="842" alt="screen shot 2017-03-21 at 12 48 21 pm" src="https://cloud.githubusercontent.com/assets/8999735/24167779/3e8246ea-0e35-11e7-9b37-b0bc99cdb755.png">

**Comment by martenson** [comment]
Good find. We should collapse the menu into hamburger sooner.

**Comment by dannon** [comment]
Ahh, yeah, I know what you mean now.  I've seen this happen when scaling a window down to test supersmall resolutions.  I didn't expect anyone to actually have windows this small, though, so hadn't made it a priority to fix.  It should be fluid when going between sizes.

**Comment by martenson** [comment]
It breaks at ~1160px width. That is not tiny. :)

**Comment by dannon** [comment]
Ya'll need bigger screens!

**Comment by martenson** [comment]
Think Mobile!

**Comment by dannon** [comment]
Mobile works really nicely with the hamburglar.

**Comment by martenson** [comment]
Think tablet mobile! :)

**Comment by dannon** [comment]
Fixed in https://github.com/galaxyproject/galaxy-hub/commit/6a11889c3b6ac884aba8fb27a17e215eb33c372a

I want to overhaul it a bit to make it more slowly go 'full hamburger', but this makes it not broken for now.

**Comment by martenson** [comment]
> I want to overhaul it

@dannon why closing this issue then?

**Comment by dannon** [comment]
Because this specific issue is fixed.  I want to avoid having many pages of open issues in this repository since it makes it harder to keep track of what needs fixing.

**Comment by martenson** [comment]
@dannon so right now we have a known reported issue 'fixed' by less than ideal approach (making invisible menu for <1200px wide viewport) and no track of the problem in Github issues.

I think you are overly aggressive in closing issues in the hub lately.

**Comment by dannon** [comment]
It 'broke' at 1200 before by looking wonky and making it larger, obscuring the page beneath, which is why I chose that.  This particular issue is fixed, and I don't think 'in a less than ideal approach'.

Anyway, if it'll allow us to move on, I'll make an issue for building a more responsive nav.  If you want to work on that, please do.

**Comment by jxtx** [comment]
@martenson What do you mean by invisible menu? We switch to a "hamburger" menu when the viewport is too narrow to fit the menu. This is a pretty standard way to deal with tablets no? Do you want multiple breaks?

**Comment by dannon** [comment]
@jxtx Multiple breaks is what I propose in #189

**Comment by martenson** [comment]
@jxtx my point is that I do not think this is a good solution to a menu:
![screenshot 2017-03-21 16 29 43](https://cloud.githubusercontent.com/assets/1814954/24169331/a3a8cf1c-0e53-11e7-8ad5-911e11bc5a01.png)
and thus closing this issues is imho premature.
