### ISSUE TITLE
High ascii and unicode symbols

### ISSUE THREAD

**Issue by davebx** [galaxyproject/galaxy-hub#190]
I'm working on changing those hub-wide to their HTML entity counterparts, but I don't want to create too many conflicts while doing so. Would it be an idea to find out what people are currently working on so I can exclude those from conversion for the time being?

**Comment by dannon** [comment]
@davebx Where are you seeing this be problematic?  I'd lean towards best practice being to leave source material in the as-typed format (I don't require people to enter html entities) and leave encoding/decoding up to metalsmith.  It's certainly possible I've allowed raw output in a template where it should be encoded.

**Comment by davebx** [comment]
@dannon I don't currently see a problem, but I do feel that it would be a good idea to prevent the possibility of problems, e.g. with browsers not correctly interpreting the declared character encoding. Then again, as you suggest, there could be better uses of my time than fixing something before it's broken.
