### ISSUE TITLE
Datatype Link Problems?

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy-hub#192]
I opened this link from Galaxy's upload widget - https://wiki.galaxyproject.org/Learn/Datatypes#Tabular_.28tab_delimited.29.

And it brought me to a page with the content:

```
<!DOCTYPE HTML PUBLIC "-_W3C_DTD HTML 3.2 FinalEN">

Surge protection
Warning:
You triggered the wiki's surge protection by doing too many requests in a short time.

Please make a short break reading the stuff you already got.

When you restart doing requests AFTER that, slow down or you might get locked out for a longer time!
```

Update: It was my first visit to the hub of the day.

**Comment by dannon** [comment]
Thanks!  Surge protection was triggered on the wiki side during conversion by pages with redirects (so, not your visit just now -- that's all static) and they'll have to be manually converted.  I'll see if I can get this one done now.

**Comment by dannon** [comment]
That page should now have parity with what was on the wiki.  Thanks for noticing this @jmchilton!
