### ISSUE TITLE
update documentation pages to reflect decommisioning of FTP upload

### ISSUE THREAD

**Issue by dlaehnemann** [galaxyproject/galaxy-hub#2081]
There used to be an option to upload data via FTP to usegalaxy.org, but this was recently decommissioned:
https://help.galaxyproject.org/t/the-usegalaxy-org-ftp-service-will-be-decommissioned-on-august-12-2022/8318

The linked discussion is closed, and I think this repository is where this should be fixed, so I am opening a new issue here.

It would be great to change all the documentation pages that reference this option to clearly notify users of the decomissioning at the top of the page. This would save lots of users a lot of time, as the forum post about the decomissioning is much less discoverable than the documentation pages suggesting that this is still available.

Here are the pages that I found, that would need amending (there might be more, I'm a bit confused by the documentation's structure):

* https://galaxyproject.org/ftp-upload/ (this is even aimed at `usegalaxy.org` explicitly)
* https://galaxyproject.org/tutorials/upload/#ftp-upload
* https://training.galaxyproject.org/training-material/faqs/galaxy/datasets_upload_ftp.html (also mentions `usegalaxy.org` explicitly)

**Comment by bgruening** [comment]
@dlaehnemann this is super helpful and thanks for digging out the pages.

Thanks.

**Comment by mschatz** [comment]
@natwhitaker will take a look

**Comment by dlaehnemann** [comment]
@natwhitaker was this changed in the respective docs? Because I can still see all the respective references to `usegalaxy.org`. But maybe this is just a matter of changes being pushed out to the actual webpages?

**Comment by natwhitaker** [comment]
@dlaehnemann Some are still being pushed! I will check later to make sure everything looks good and if not I will reopen!
