### ISSUE TITLE
Link to "Purge Histories and Datasets" is broken on Community Hub

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/galaxy-hub#212]
There is a link on [Galaxy Administration](https://galaxyproject.org/admin/) that points to [Purge Histories and Datasets](https://galaxyproject.org/admin/config/performance/Purge%20Histories%20and%20Datasets/), which is a broken link.

**Comment by dannon** [comment]
@lparsons  Thanks, fixing this now.

**Comment by dannon** [comment]
Fixed in 19006b7fb1303da61e8ff06bd3d3d8ac428c1640
