### ISSUE TITLE
redirect to headers doesn't work

### ISSUE THREAD

**Issue by hrhotz** [galaxyproject/galaxy-hub#230]
It is a minor issue, but, if I follow this old link:

https://wiki.galaxyproject.org/Admin/GetGalaxy#Become_an_Admin

I get redirected to:

https://galaxyproject.org/admin/get-galaxy/#Become_an_Admin

but end up at the top of the page. The correct redirect would be:

https://galaxyproject.org/admin/get-galaxy/#become-an-admin

Hans-Rudolf

**Comment by dannon** [comment]
I'll look into handling external links like `#Uppercase_and_Underscores` via nginx rewrites, but for internal links, I can fix those.  PR open at #235

**Comment by tnabtaf** [comment]
I Declare this one fixed.  It was fixed a couple of months ago, but (I think) I didn't close this issue at that time like I should have.

**Comment by hrhotz** [comment]
well, it doesn't look like fixed to me (sorry to be a pain in the neck). 
I am still being redirected to https://galaxyproject.org/admin/get-galaxy/#Become_an_Admin
and ending up at the top of the page. 

However, as I said it is a minor issue, and I will not reopen it
