### ISSUE TITLE
Pictures not available on galaxy 101

### ISSUE THREAD

**Issue by acavalla** [galaxyproject/galaxy-hub#234]
The pictures don't load and any link on the old wiki to galaxy 101 directs back to the new wiki. This is a problem since without the pictures, it's not clear which settings should be chosen. Therefore when I get a different answer, it's unclear which incorrect settings it is due to.
@dannon

**Comment by martenson** [comment]
@acavalla I see pictures in Galaxy 101 well (https://galaxyproject.org/tutorials/g101/) which page are you referring to?

**Comment by acavalla** [comment]
oh that one works! I was looking at it here: https://github.com/nekrut/galaxy/wiki/Galaxy101-1
Apologies for the confusion & thank you for your help!

**Comment by dannon** [comment]
@acavalla Great, glad it's working for you!
