### ISSUE TITLE
SIG requirements - to who 'the nominated GCB representative' should be provided

### ISSUE THREAD

**Issue by lldelisle** [galaxyproject/galaxy-hub#2374]
Would be good to explicitely give a contact to who 'the nominated GCB representative' should be provided:
https://github.com/galaxyproject/galaxy-hub/blob/22ecb045c0507c078e3a82187c6cc0c9f1f809f2/content/community/governance/gcb/index.md?plain=1#L62

**Comment by bgruening** [comment]
Would it be bad to put this contact address on the homepage?

**Comment by lldelisle** [comment]
No this seems good. I will try to clarify it.
