### ISSUE TITLE
Link to project logo in history tour is broken

### ISSUE THREAD

**Issue by infB** [galaxyproject/galaxy-hub#239]
The link to the first dataset from the galaxy tour "History Introduction - A detailed introduction to the Galaxy History" is broken:

https://wiki.galaxyproject.org/Images/GalaxyLogo?action=AttachFile&do=get&target=galaxy_project_logo.jpg

**Comment by dannon** [comment]
@infB Thanks, I'll fix the link!

**Comment by dannon** [comment]
I've fixed this on the tour side via https://github.com/galaxyproject/galaxy/pull/4061, thanks again @infB!
