### ISSUE TITLE
Broken link https://galaxyproject.org/projects/small-scale-admins/ 

### ISSUE THREAD

**Issue by vladvisan** [galaxyproject/galaxy-hub#2391]
https://galaxyproject.org/projects/small-scale-admins/ is a broken link, and yet still referenced https://galaxyproject.org/search/?q=small%20scale%20admin#gsc.tab=0&gsc.q=small%20scale%20admin&gsc.page=1

**Comment by bgruening** [comment]
Thanks for reporting. @hrhotz put a redirect in place. Thanks!
