### ISSUE TITLE
Speed up metalsmith-autotoc during build process

### ISSUE THREAD

**Issue by tnabtaf** [galaxyproject/galaxy-hub#240]
`% make build serve`

takes around a minute on my laptop.  ~ 35 seconds of that is spent in `metalsmith-autotoc`.  I bet this metalsmith plugin has not been strenuously optimized.  Making this go faster is not urgent, but I bet the whole Metalsmith (and Galaxy) community would thank the intrepid JavaScript expert who made this happen.

**Comment by jxtx** [comment]
Replace this stuff: https://github.com/anatoo/metalsmith-autotoc/blob/master/index.js#L123

With cheerio: https://www.npmjs.com/package/cheerio

**Comment by tnabtaf** [comment]
Thanks @jxtx.

**Comment by dannon** [comment]
Should be fixed with #244
