### ISSUE TITLE
Update Galaxy citation

### ISSUE THREAD

**Issue by lldelisle** [galaxyproject/galaxy-hub#2636]
I guess this:
https://github.com/galaxyproject/galaxy-hub/blob/f6f55a97989dad1938ee7627aed7136e51952c91/content/home/research.yml#L19-L20
Should be updated to https://doi.org/10.1093/nar/gkae410

**Comment by dannon** [comment]
@lldelisle Yep, absolutely, and there are a few more spots -- I have a branch addressing this, let me PR it
