### ISSUE TITLE
Executing a workflow and tagging several chained steps will result in the overwriting of previous step output tags

### ISSUE THREAD

**Issue by yvanlebras** [galaxyproject/galaxy-hub#264]
Hi everyone, I see another potential issue related to tagging workflow step in "configure output" / "Tags". If at a step X I add a tag #lovegalaxy and that in the step x+1 I add #loveiuc, then executing the wf on a history will result for the x+1 output step on a uniq tag (here #loveiuc). It seems that the previous one is erased...

**Comment by nsoranzo** [comment]
Wrong repo, comment copied to https://github.com/galaxyproject/galaxy/issues/3730 .
