### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ianschenck** [galaxyproject/galaxy-hub#2681]
The link to donate here: https://galaxyproject.org/jxtx/foundation/ "Donate" is broken.

**Comment by dannon** [comment]
@ianschenck Thanks! The JXTX Foundation now has a site at https://jxtxfoundation.org/. I'll make a note of that on this hub page and set up a redirect. Moving forward, donation information will always be available at https://jxtxfoundation.org/donate/. The foundation is currently using Zeffy to handle donations, and you'll find the link there.
