### ISSUE TITLE
Image links are wrong in the feed

### ISSUE THREAD

**Issue by arash77** [galaxyproject/galaxy-hub#2721]
It seems that the Atom feed generated at https://galaxyproject.org/eu/feed.atom contains incorrect image URLs, causing the images to not load properly.
For example, in the post ["What do you want to know about Galaxy-EU? Our first 'Ask us anything' Q&A session"](https://galaxyproject.org/news/2024-07-29-ask-us-anything-report/), the image URL is currently:
`https://galaxyproject.org/news/2024-07-29-ask-us-anything-report/questions_1.png`
However, it should be one of the following:
* `https://galaxyproject.org/assets/static/questions_1.175c05c.0caec253b2ef2e0beaac0cb1f447d02c.png`
* `https://raw.githubusercontent.com/galaxyproject/galaxy-hub/master/content/news/2024-07-29-Ask-Us-Anything-report/questions_1.png`

This issue was first identified while using the Atom feed to create automated Galaxy social PRs: https://github.com/usegalaxy-eu/galaxy-social/pull/86#discussion_r1697182311.

Could you please look into this?

Thank you!

**Comment by bgruening** [comment]
@dannon do you have a clever idea here?

**Comment by arash77** [comment]
I realized that images not relatively addressed (external images) in the Markdown, remain unchanged. For example, in this post:
https://galaxyproject.org/news/2024-07-08-galaxy-social/
The image mentioned in the Markdown is:
https://github.com/arash77/galaxy-hub/assets/2973722/c8de8bdf-3cee-466f-aea3-d2462b4bc88f
This image remains consistent across the website and in the feed.

**Comment by dannon** [comment]
Alright, I finally had a minute to look at this, sorry for the delay @arash77, @bgruening

The staging I was referring to (out of band in either dev meeting or chat, wherever) is here:  https://github.com/galaxyproject/galaxy-hub/blob/master/src/build/run.mjs#L95.  This is working.  It stages the source file `content/news/2024-07-29-Ask-Us-Anything-report/questions_1.png` to `dist/content/news/2024-07-29-Ask-Us-Anything-report/questions_1.png` at the end of the build, for direct access.  That dist dir is what we end up publishing as galaxyproject.org.

Note the case.

https://galaxyproject.org/news/2024-07-29-ask-us-anything-report/questions_1.png

Which is generated in the feed, fails, but the following URL exists and works.

https://galaxyproject.org/news/2024-07-29-Ask-Us-Anything-report/questions_1.png

I need to double check we're not relying on the case anywhere else, but we should probably just stick to forcing lowercase paths (on staging, automatically doable) and move on.

**Comment by arash77** [comment]
Thank you, Dannon! So, this issue only happens with the images and not the posts?

**Comment by bgruening** [comment]
Indeed its https://galaxyproject.org/news/2024-07-26-shiny-phyloseq-on-EU/alpha-div.gif (available) vs. https://galaxyproject.org/news/2024-07-26-shiny-phyloseq-on-eu/alpha-div.gif (in the feed) ... :scream:

**Comment by dannon** [comment]
Right.  I'm testing adjusting the staging to create all outputs at the `toLowerCase` paths, standardized.

**Comment by arash77** [comment]
It seems that the problem still exists in the feed with this image:
https://galaxyproject.org/news/2024-08-14-galaxy-in-research/GalaxyInResearch_Jain2024.png
https://github.com/galaxyproject/galaxy-hub/tree/master/content/news/2024-08-14-GalaxyInResearch

**Comment by dannon** [comment]
I wonder if that's a fluke of that branch being before the other fix was merged?  When I build locally I do see:
```
[dannon@inneoin:~/work/galaxy-hub] find dist -name "GalaxyInResearch_Jain2024.png"                        master
dist/news/2024-08-14-galaxyinresearch/GalaxyInResearch_Jain2024.png
```

so that link *should* work.  Let me trigger a manual rebuild.

**Comment by arash77** [comment]
It seems they are all fixed! Thank you @dannon.

**Comment by arash77** [comment]
There is also a problem with this post:
https://galaxyproject.org/news/2024-09-05-galaxy-in-research-lin2024/
The image doesn't exist in the feed:
https://galaxyproject.org/news/2024-09-05-galaxy-in-research-lin2024/Figure_Lin2024.jpeg
cause break in the https://github.com/usegalaxy-eu/galaxy-social/pull/107
