### ISSUE TITLE
Layout of UseGalaxy individual pages has gone askew

### ISSUE THREAD

**Issue by GarethPrice-Aus** [galaxyproject/galaxy-hub#2725]
The wrapping of section headings on each of the usegalaxy.* pages, accessed from https://galaxyproject.org/use/ is not displaying clearly. See usegalaxy.org (https://galaxyproject.org/use/usegalaxy-org/):
![image](https://github.com/user-attachments/assets/31b9da8e-4b21-405d-bb8d-9b3b55c750c4)

Same for .eu, .fr and .org.au. Another example from https://galaxyproject.org/use/usegalaxy-au/:
![image](https://github.com/user-attachments/assets/6d073321-c534-452e-816a-8c979ae12ca5)

The Comments, User Support, Quotas and Citations headings need alignment with their associated text.

**Comment by dannon** [comment]
Should be fixed with #2727, thanks for the report!

We should take care not to apply wide-matching styles like that in pages -- either scope locally to specific elements in the local markdown, or use scoped styling in a vue component as appropriate.

**Comment by PatCapon39** [comment]
Thanks @dannon! It looks like the bullet spacing is off, the spacing after the first bullet is greater than the other bullets (see image). Can the first bullet be brought into line with the other ones?

<img width="646" alt="Screenshot 2024-08-08 at 7 30 53 am" src="https://github.com/user-attachments/assets/e194a62a-f350-4981-9451-d8b066ebaad7">

**Comment by dannon** [comment]
Well that's an interesting one -- didn't see that, we can definitely fix it.  I'll take a look

**Comment by PatCapon39** [comment]
Nice, thanks! If you're tinkering with that page, I just submitted PR #2729 to fix a broken hyperlink in the 'sponsors' section too
