### ISSUE TITLE
Broken wiki link

### ISSUE THREAD

**Issue by jamesabbott** [galaxyproject/galaxy-hub#274]
https://galaxyproject.org/admin/data-integration/ includes a link to  which appears broken. Near the top of the page:

"Fetch Alignment" tools data prep: [Reference MAFs](https://galaxyproject.org/admin/data-integration/Admin%2FReferenceMAFs)

**Comment by jamesabbott** [comment]
...and another one....

on https://galaxyproject.org/admin/data-integration/:

Note that as of early 2014, more than a builds.txt file change is needed to establish a new reference genome. If not using Data Managers , you must make the necessary changes/additions to the new [Data Tables](https://galaxyproject.org/admin/data-integration/Admin%2FTools%2FData+Tables) or use the alternative configuration file (described on that same Data Tables wiki, near the end).

the 'Data Tables' link is broken...

**Comment by jamesabbott** [comment]
Ok...let's rephrase that...
Every internal link on that page seems to be broken...

**Comment by aliceminotto** [comment]
link in #238 is still broken as well (looking for https://galaxyproject.org/Admin/Tools/ToolDependencies)

**Comment by blankenberg** [comment]
https://galaxyproject.org/admin/tools/Data%2520Tables.md linked from https://galaxyproject.org/admin/tools/data-managers/ should perhaps point to https://galaxyproject.org/admin/tools/data-tables/

**Comment by baberlevi** [comment]
seems this may be the old link for 'Data Tables' - haven't found a new one:
https://moin.galaxyproject.org/Admin/Tools/Data%20Tables

**Comment by baberlevi** [comment]
Looks like issue #99 has the correct link for data tables: https://galaxyproject.org/admin/tools/data-tables/
