### ISSUE TITLE
Add "How to Edit the Galaxy Hub using GitHub Web Editor" doc

### ISSUE THREAD

**Issue by tnabtaf** [galaxyproject/galaxy-hub#307]
Hello all,

I'm working on expanding the "how to edit the hub" documentation.  Currently it's in the [readme branch](https://github.com/galaxyproject/galaxy-hub/tree/readme), and it's not ready for merging.

Currently (as previously discussed with @dannon) everything is in the top level [README.md file](https://github.com/galaxyproject/galaxy-hub/blob/readme/README.md)

Other than polish, I don't expect to add much to the "Submiting your first edit through the GitHub web interface" section.  I'm currently working on the "General Guidelines, Structure, and The Details" section.

Any suggestions on how to highlight guidelines so they stand out?  This page isn't rendered on the site so we are limited to GFM and maybe some HTML.

Feedback is encouraged.

**Comment by dannon** [comment]
Nice!  These enhanced general guidelines were on my list, too, and you've done a better job than I would for sure!

I do like keeping it all in the readme.  As far as highlighting, maybe a (?) icon or something of the sort appears on the published pages when you hover over the Edit link?

So, I'm on a page, I think I want to make changes.  I see Edit at the top and go to click it.  As I move my mouse over it, `:github: Edit` slides to the left and there's a little ? in a circle that I can also click, for more details?

**Comment by martenson** [comment]
I would recommend using the [contributing file](https://opensource.guide/starting-a-project/#writing-your-contributing-guidelines) that github directly supports. Superlong readmes feel cumbersome.

**Comment by dannon** [comment]
The contributing file is nice when people know to look for it, but my concern there was that I'm not sure that's the audience that'd need this help will know to look for it?

If we do something similar to what I mention above and link directly to instructions, I could see splitting the README and using a CONTRIBUTING, too, though.

**Comment by martenson** [comment]
I doubt we can make it more visible than GitHub did

![contributing-guidelines](https://user-images.githubusercontent.com/1814954/30229654-c7a2300a-94b0-11e7-892d-702b0bb6268b.jpg)

**Comment by dannon** [comment]
Again, from the perspective of someone used to editing a wiki, I don't know that that link gets clicked.  I feel like there's a stark difference in the language used between "guidelines for contributing" and "Not sure how to edit?  Click here!".

**Comment by tnabtaf** [comment]
@dannon, @martenson I'll give both approaches a try.  That's easy.

**Comment by tnabtaf** [comment]
A couple of things:

- I've split the doc into README and CONTRIBUTING files.  It is easy to merge it back.  However, I prefer putting the editing help in the CONTRIBUTING file. 
- I've started adding stuff to the page metadata section.  I've put the news item metadata help in two formats: as a bullet list, and as a table.
  - To my surprise, I prefer the bullet list, even though it takes up twice as much space.

Feedback is encouraged.

**Comment by tnabtaf** [comment]
**@dannon: I think this is ready to go, and unless there is a discussion, I'll turn this in to pull request on Friday.**

Random bits:

- It isn't done yet, but I think it's ready for publication.
- Right now it focuses on the GitHub web interface instead of editing a local copy. I barely touched the local install section.
  - I'll get to that later this month, on a fresh laptop and/or VM.
- This splits it into README and CONTRIBUTING files.  I lean towards having them split, and I suggest we try it that way first.
- *I don't think I have the JavaScript chops to set a link in the menu in less than two hours.  Any chance I can get you to do that in this branch?*

Finally, if and when the proposed PR is submitted, I'll also rename this issue to be something like

- *Add How to Edit the Galaxy Hub using GitHub Web Editor doc*

That better reflects what this issue ended up being about.  When I start work on the local copy doc, I'll create an issue titled something like

- *How to edit the Galaxy Hub using a local copy doc*

Thanks

**Comment by dannon** [comment]
Yep, I can add the link, will work on something spiffy in a few.

To be clear I'm totally fine with splitting the docs into the two separate files; my preference for a single file was based on the hunch that it is easier for a GitHub novice to *find* the info that way, since it's highlighted on the main repository page *without* signing in to GitHub or forking (at which point you'd get the scary (to me) "Review the contribution guidelines!").  A direct link like we've discussed mitigates that worry.

**Comment by dannon** [comment]
Oh, and feel free to PR like right now if you want.  There's no need to wait for the finished, polished branch --  WIP PRs are totally fine (at least in our Galaxy space) and are a great way to keep visibility high and encourage collaboration.

**Comment by tnabtaf** [comment]
Thanks, and will do.

**Comment by tnabtaf** [comment]
See PR #308.  And changing the name of this issue.

**Comment by tnabtaf** [comment]
And merged.  Thanks @martenson.
