### ISSUE TITLE
Fix GCC Pages

### ISSUE THREAD

**Issue by tnabtaf** [galaxyproject/galaxy-hub#320]
I'm in the process of creating a GCC home page (`/src/gcc/index.md`) that will link to all the past GCCs, and have general info about GCCs.  But GCC2014, GCC2013, and GCC2012 didn't make the transition very well.  And the GCC2011 and GDC2010 websites can no longer be reached!

So, i'm creating this issue to say "I'm actively working on this."  I'll clean up 2012-2014, and track down 2010-2011.

**Comment by hrhotz** [comment]
@tnabtaf

wrt to GDC2010: what about this page: https://moin.galaxyproject.org/Events/GDC2010  ?
I also have some e-mails with actual schedule, list of participants, etc   let me know, if you nedd any of this.

Hans-Rudolf

**Comment by tnabtaf** [comment]
@hrhotz: I found both GDC2010 and GCC2011 in the filesystem guts.  So, I now have the source material.  Trying to decide how much to reconstruct, or if just the presentations would be enough.  Thoughts?

**Comment by tnabtaf** [comment]
With some help from @natefoo, GDC2010, GCC2011, and GCC2012 are back to being useful.  More or less.

**Comment by hrhotz** [comment]
@tnabtaf: I would reconstruct as much as possible. It is our history.

**Comment by tnabtaf** [comment]
GCC2013 and GCC2014 hub pages are better now too.  GCC2015 and GCC2016 will be easier because they had a minimal presence on the wiki.

@hrhotz, I'd like to fully restore everything to it's former glory, but, um, I think it's worth prioritizing the program and uploaded slides.  So, that's what I've done.  I might revisit GDC2010 (by far the worst case) at some point.

**Comment by tnabtaf** [comment]
Updated GCC2015 and GCC2016 Hub pages.  Declaring victory.
