### ISSUE TITLE
Remove an empty file from a dataset collection

### ISSUE THREAD

**Issue by Mataivic** [galaxyproject/galaxy-hub#334]
Hello,

I am currently building a tool in Galaxy and I'm using dataset collections for the output files. Sometimes, the tool fails for a given input file and the corresponding output file in the collection is empty (before, it caused a crash but I have implemented some error management).

I would like to know if it possible to remove an empty file from a collection, or best, to prevent an empty file to be added to a collection.

Thanks !

**Comment by bgruening** [comment]
@Mataivic this is probably the wrong channel to ask. Better on gitter, tools-iuc or biostars. Sorry for the slow response. Under "collection operation" is a tool called "Filter failed datasets from a list", this should help you.
