### ISSUE TITLE
How to move files between Galaxy servers (any!) link is broken - page not found

### ISSUE THREAD

**Issue by SaveDaVinyl** [galaxyproject/galaxy-hub#335]

**Comment by martenson** [comment]
note: it is from this https://galaxyproject.org/support/ page and this link https://galaxyproject.org/community/log/2016/moving-data-between-galaxies/

**Comment by tnabtaf** [comment]
Fixed in commit ec9c0dc6b5f02bf2ccfb65fd6ddb76d0e13c7b74.  @SaveDaVinyl thanks for reporting this.
