### ISSUE TITLE
Broken link to docs on composite datatypes

### ISSUE THREAD

**Issue by pjbriggs** [galaxyproject/galaxy-hub#340]
The link to documentation on composite datatypes (at https://galaxyproject.org/Admin/Datatypes/Composite%20Datatypes) appears to be broken.

I followed this link from the `planemo` documentation on ReadTheDocs (in this section: http://planemo.readthedocs.io/en/latest/writing_how_do_i.html#test-composite-dataset-contents) so it might be a bug in the `planemo` docs rather than the Galaxy hub.

**Comment by nsoranzo** [comment]
Fixed by https://github.com/galaxyproject/planemo/pull/1020
