### ISSUE TITLE
broken links in public-galaxy-servers

### ISSUE THREAD

**Issue by haruosuz** [galaxyproject/galaxy-hub#341]
The following links are broken.

----------

### [VirAmp](https://galaxyproject.org/public-galaxy-servers/viramp/)
Comments
from Wan et al.: http://www.gigasciencejournal.com/content/4/1/19 "404 Not Found"
should be
https://www.ncbi.nlm.nih.gov/pubmed/25918639

### [BioMaS](https://galaxyproject.org/public-galaxy-servers/biomas/)
Links
BioMaS Galaxy http://galaxy.cloud.ba.infn.it:8080 "Internal Server Error"
Comments
BioMaS https://galaxyproject.org/BioMa/ "Page Not Found"

### [BitLAB](https://galaxyproject.org/public-galaxy-servers/bitlab/)
BitLAB Galaxy https://pistacho.ac.uma.es/galaxy/ "502 Bad Gateway"
There is an extensive tutorial on how to use the server. http://www.bitlab-es.com/gecko/documents/GalaxyGuidedExercise.pdf

----------

### [ODoSE](https://moin.galaxyproject.org/PublicGalaxyServers#ODoSE)
Link:
ODoSE: Ortholog Direction of Selection Engine
http://www.odose.nl
"503 Service Unavailable"

### [BISTRO](https://moin.galaxyproject.org/PublicGalaxyServers#BISTRO)
Link:
BISTRO Galaxy http://galaxy.bioinfo-bistro.fr/galaxy/
PipeAlign workflow http://galaxy.bioinfo-bistro.fr/galaxy/u/kress/w/pipealign-2
"503 Service Unavailable"

----------

### [MetaDP](http://metadp.cn:7001/)
[MetaDP: a comprehensive web server for disease prediction of 16S rRNA metagenomic datasets](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5334392/)

I wonder if MetaDP, ODoSE, and BISTRO have been removed from Publicly Accessible Galaxy Servers?

----------

**Comment by dannon** [comment]
@haruosuz Sorry I do not follow where the links are from.  I'm looking through https://galaxyproject.org/public-galaxy-servers/, which is the public server homepage now, and don't see the old, broken moin links.  Can you elaborate?

**Comment by haruosuz** [comment]
@dannon Thank you for your reply. The links are from
- VirAmp https://galaxyproject.org/public-galaxy-servers/viramp/
- BioMaS https://galaxyproject.org/public-galaxy-servers/biomas/
- BitLAB https://galaxyproject.org/public-galaxy-servers/bitlab/

- ODoSE https://moin.galaxyproject.org/PublicGalaxyServers#ODoSE
- BISTRO https://moin.galaxyproject.org/PublicGalaxyServers#BISTRO

**Comment by dannon** [comment]
@haruosuz Ahh!  I see, I misunderstood.  moin.galaxyproject.org is deprecated and unmaintained, but I will look into the other three.

**Comment by dannon** [comment]
@haruosuz Ok, I fixed what links I could, but it looks like the whole bitlab-es site is offline, and the biomas one is very slow to respond.  We can check back later to see if the downtime is temporary, or permanent, and then take action (remove them from the list here, if they're gone forever).

**Comment by haruosuz** [comment]
@dannon Thank you.
- [BitLAB](https://galaxyproject.org/public-galaxy-servers/bitlab/) site is now accessible.
- "Pylogenetics" should be "Phylogenetics" at https://galaxyproject.org/public-galaxy-servers/ and https://galaxyproject.org/public-galaxy-servers/osiris/

**Comment by dannon** [comment]
Fixed the Pylogenetics typo https://github.com/galaxyproject/galaxy-hub/commit/422c172cffa291dd27ac4a2118f41d9dd80b4481.

Thanks for the reports!  If you'd like to, definitely feel free to change any of this sort of stuff on your own, too!  We want folks to treat the galaxy hub like a wiki, making edits anytime they'd like.
