### ISSUE TITLE
Broken link on tutorial main page (Processing many samples at once)

### ISSUE THREAD

**Issue by TKlingstrom** [galaxyproject/galaxy-hub#342]
As per instructions on the broken link page:

When visiting
https://galaxyproject.org/tutorials/
All links are broken.

**Comment by dannon** [comment]
@TKlingstrom Thanks for noticing this; it should be fixed now.  The content had been migrated to the new /learn/ hub page, but we left this one dangling.  How did you find the old page, out of curiosity?

**Comment by TKlingstrom** [comment]
I think it may have been because the tutorials are still having URL:s such as "https://galaxyproject.org/tutorials/rb_rnaseq/". As the files are stored in a file structure it is natural to assume that  "https://galaxyproject.org/tutorials/" is the menu page and it looks likes it should be the page. Having an automatic redirect to the new /learn page would sort it out I guess.

**Comment by dannon** [comment]
@TKlingstrom Got it, just wanted to make sure there wasn't actually a navigable reference to /tutorials/ I needed to fix as well.  It has been on my list for a bit to add a file-based redirect for hub pages; I'll bump that up.

**Comment by dannon** [comment]
(and, followed up with https://github.com/galaxyproject/galaxy-hub/commit/a0911012d6c33055d905400420d6ef9d6c868a2e, which implements this basic redirect functionality)
