### ISSUE TITLE
Community Hub Contribution Convergence (CHCC), Thursday December 8

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy-hub#35]
Content for this site was automatically converted from the old MoinMoin and Creole markup to Markdown, and many other things were also cleaned up in the process. However, the automatic translation stumbled in some places and the cleanup and general restructuring are far from done.  We also aren't yet taking advantage of Metalsmith to render semi-structured content and page metadata.

## The Community Hub Contribution Convergence (CHCC): Thursday December 8

To address these issues we are holding the Community Hub Contribution Convergence (CHCC) online this week on Thursday December 8.  The goals of CHCC are to

* Get participants up to speed on how to update the new site.
* Create / improve documentation on how to update the new site.
* Fix translation errors and things that were accidentally dropped
* Generally reorganize and update documentation.
* Drop obsolete material
* Work out plans and best practices for supporting semi-structured content and page metadata.

CHCC will use this issue to coordinate work, and a Gitter channel for communication during the event.  Interested?  Please join us. 
The *Hub* uses GitHub Flavored Markdown for markup,  and [Metalsmith](http://metalsmith.io) for web site rendering and for semi-structured content (such as the [Events](src/events) page). The new platform offers the strength of our old wiki (easy contribution) with a markup language many more people know, easy programmatic access, and all the strengths of GitHub.

Once the Hub is in better shape it will become the [galaxyproject.org](https://galaxyproject.org) site.  Until then you can find it at [new.galaxyproject.org](https://new.galaxyproject.org).  Once the move is complete the [old wiki](https://wiki.galaxyproject.org) will be shut down.

## Issues

Please add [issues](https://github.com/galaxyproject/galaxy-site/issues) as you identify them.  In general, any open issue is a good target to work on.

**Comment by bgruening** [comment]
Welcome everyone!

**Comment by dannon** [comment]
Here's a handle to the Gitter channel: https://gitter.im/galaxyproject/Lobby
