### ISSUE TITLE
Create a subdirectory for user pages?

### ISSUE THREAD

**Issue by tnabtaf** [galaxyproject/galaxy-hub#36]
Hi All,

MoinMoin user pages were translated directly to the new site, meaning that they all exist at the top level of the /src directory.  I'd like to propose that we create a separate directory for user pages, move them all there, and then update any links in the site to go to the new pages.  This can all be done programmatically.

We could also change the page naming convention while we are at it.  It is currently FirstLast.  

**Open Questions:**

**1. What do people think of the proposal?**

**2. Where should they moved to if we move them?**

A couple of ideas come to mind:

```
/src/People/
/src/Community/
/src/Community/People/
```

**3. Should we change the naming convention?**

**Comment by dannon** [comment]
+1 to pushing it into ```/People/```, or ```/Community/People/```, though perhaps we want to standardize to lowercase, a-la #29 ?

**Comment by tnabtaf** [comment]
My preferences:

**1. What do people think of the proposal?**

:+1

**2. Where should they moved to if we move them?**

`/src/People/` :+1 

**3. Should we change the naming convention?**

Hmm.  We could change these to be people's GItHub names.  The Galaxy page would not replace their home page, but people could have one if they want a Galaxy specific page.

A specific proposal:

1. We use the MoinMoin names by default
2. Whoever does the translation (and I volunteer), contacts people before doing it, and asks them what they would like, suggesting github name as an option.

**Comment by tnabtaf** [comment]
@dannon I've been using Caps for DirectoryNames since 1993.  However, I actually have no opinion on caps vs non-caps.

**Comment by bgruening** [comment]
> 1. What do people think of the proposal?

:+1:

> 2. Where should they moved to if we move them?

/community/people/ :+1:

3. Should we change the naming convention?

lowercase

**Comment by afgane** [comment]
My preferences:

**1. What do people think of the proposal?**

👍 

**2. Where should they moved to if we move them?**

`/src/people/` 👍  (just because it's a little shorter but `/src/community/people` is fine too)

**3. Should we change the naming convention?**
lowercase; I'd also go for full name joined with a `-` (e.g., enis-afgan) vs. Github ID.

**Comment by tnabtaf** [comment]
Going with 

`/src/people/`

for the directory name.  Waiting on decisions in #39 to figure out what the default new naming convention is for each person page.  That is, should EnisAfgan become

`/src/people/enis-afgan` or `/src/people/enis_afgan` or `/src/people/enisafgan`?

Also planning to give people these choices

- `first_last` (assuming _) - the default action if we don't get a response.
- `githubname` - for example, the DaveClements page would become the `/src/people/tnabtaf` page.
- Drop their page and change any in-hub links to point to an external page
- Drop their page and change any in-hub links not to be links any more.

**Comment by afgane** [comment]
For the name structure, my votes go for the hyphenated version, followed by
the one-word option. Underscores are not loved much in URLs:
https://www.woorank.com/en/blog/underscores-in-urls-why-are-they-not-recommended

**Comment by dannon** [comment]
Let's go with hyphenated, it's pretty much standard.

**Comment by dannon** [comment]
@tnabtaf I actually have outstanding work that interacts with this change a lot (in the partials branch), so I can update my script to change these across the board.

So, directories like ```/src/GalaxyTeam/DannonBaker/``` will be ```/src/galaxy-team/dannon-baker/```, and I'll update references across the repo.

**Comment by bgruening** [comment]
@dannon shouldn't this be `/src/people/galaxy-team/dannon-baker/`?
I would like to see many different teams, like IUC, NLP, GalaxyP ... and imho they should be under people, or `/src/teams/`

**Comment by dannon** [comment]
@bgruening Sure, that was just an example.  I'm not moving anything, just handling the renaming, *then* we can move stuff.

**Comment by dannon** [comment]
@bgruening Regarding teams, I'd much rather see everyone in ```/src/people/```.  If we do want to build collections of people for display, teams, we should do something like 
```
---
title: Firstname Lastname
collection: team_iuc
collection: team_galaxy
...
---
```
in the yaml frontmatter for the person.  Then we can have them show up on team pages as appropriate, people can belong to multiple, and so on.

**Comment by bgruening** [comment]
Yes!

**Comment by tnabtaf** [comment]
So, we'll go with hyphens, and @dannon would prefer to do the change.  Dannon I'll send the email below to everyone that has a person page and a wiki account.  Can we hold off on the moving/renaming until later in the week?  (I also have a script that can do this, but then we'd have merge challenges.)

Dannon, Here's the current email.  I'll probably send these our within and hour from now.  I'll send you python dicts with their mappings and responses by, say the end of this Wednesday.


Dear Galaxy Wiki User,

As you may be aware, we are in the process of moving the Galaxy Wiki to a new platform we are calling the Galaxy Hub. As a part of this effort, we are also moving user pages from the old wiki to the new hub.

In the wiki, user pages had to occur at the top level. In the Hub we are consolidating them in the "people" directory and shifting to all lower case for page names.

Unless we hear from you in the next few days, your user page will move from: 
  https://wiki.galaxyproject.org/DaveClements

to 
  https://new.galaxyproject.org/people/dave-clements

which will eventually become just 
  https://galaxyproject.org/people/dave-clements

However there are other options too:

1. Use a different (all lower case) name. This could be your GitHub id.
1. Drop your user page and set any links to it to point to an external page.
1. Drop your user page and convert links to it to be plain text.

If you are interested in any of these other options, please let me know which one, and if appropriate, what the page name should be, or where any links should point. 

Thanks,

Dave C

**Comment by dannon** [comment]
@tnabtaf I guess it could wait, but I was going to do this for *everything* on the site, not just people pages, in a single pass.  How about we do that, and afterwards encourage people to rename if it doesn't work for them?

**Comment by tnabtaf** [comment]
I think I missed your post by seconds.  :-/

Emails have gone out.

I think it's fine if you just do the move.  If people want another option, they will let me know and I can do that in a cleanup stage.  So, go for it.

**Comment by dannon** [comment]
Yeah, I'm going to just do it and we can do any requested manual curation later.

**Comment by tnabtaf** [comment]
There are 44 person pages.   I have a python dict with the mapping in it, do you want it?

**Comment by dannon** [comment]
I don't think so, since I'm applying this change to the entire site.

**Comment by tnabtaf** [comment]
Moved all person pages from top level directory to the new people subdirectory.  See the [commit](https://github.com/galaxyproject/galaxy-hub/commit/d3d23491dbe09e9dafd97fbe2cf0bf42d1dfce50)

**Comment by dannon** [comment]
@tnabtaf Thanks for following up on this, I forgot to roll it into the hyphen mass-move, good catch!
