### ISSUE TITLE
add flyer to website

### ISSUE THREAD

**Issue by nicolevasilevsky** [galaxyproject/galaxy-hub#367]
The current version of the flyer is here, do you want to add it to the website?

[GCCBOSC_v4_2018-01-22.pdf](https://github.com/galaxyproject/galaxy-hub/files/1653690/GCCBOSC_v4_2018-01-22.pdf)

**Comment by tnabtaf** [comment]
Hi @nicolevasilevsky 
Closing this, as we are now a couple of iterations ahead of this version.  With apologies.
