### ISSUE TITLE
Broken link in community hub

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy-hub#369]
The following link:

https://galaxyproject.org/Admin/Datatypes/Composite%20Datatypes

is broken. The page that has this link is the planemo documentation here (right above the anchor):

http://planemo.readthedocs.io/en/latest/writing_advanced.html#dynamic-numbers-of-outputs

If you search on the last page for `For more information visit Composite Datatypes` you should fine it.

Thanks!

**Comment by tnabtaf** [comment]
HI @pcm32,  This should be pointing at 

https://galaxyproject.org/admin/datatypes/composite-datatypes/

which has now been updated itself to redirect to 

https://docs.galaxyproject.org/en/latest/dev/data_types.html

But, the Planemo doc has already been updated to point to

https://docs.galaxyproject.org/en/master/dev/data_types.html#composite-datatypes

So, 

1. I am closing this issues, 
2. And I won't get my first Planemo PR either.  :-(

Cheers, Dave C
