### ISSUE TITLE
Semi-Structured Content: Best Practices

### ISSUE THREAD

**Issue by tnabtaf** [galaxyproject/galaxy-hub#38]
Hi All,

One of the reasons for using Metalsmith in the new site is that it is much more powerful when it comes to rendering semi-structured content than was MoinMoin.  By semi-structured content I mean directory pages such as:

* [Community Deployments directory page](https://github.com/galaxyproject/galaxy-site/blob/master/src/Community/Deployments/index.md) which did not translate at all, [Community Deployments entries](https://github.com/galaxyproject/galaxy-site/tree/master/src/Community/Deployment) which translated, but not the metadata
* [Community Logs directory page](https://github.com/galaxyproject/galaxy-site/blob/master/src/Community/Logs/index.md), [Community Log entries](https://github.com/galaxyproject/galaxy-site/tree/master/src/Community/Log)
* [Public Galaxy Servers](https://github.com/galaxyproject/galaxy-site/blob/master/src/PublicGalaxyServers/index.md), [Semi-Public Galaxy Services](https://github.com/galaxyproject/galaxy-site/blob/master/src/SemiPublicGalaxyServers/index.md)
* [Galaxy Trainers](https://github.com/galaxyproject/galaxy-site/blob/master/src/Teach/Trainers/index.md), [Galaxy Training Materials](https://github.com/galaxyproject/galaxy-site/blob/master/src/Teach/Resources/index.md)

Some of these used MoinMoin's semi-structured support. These did not translate well, but should be easiest to adapt. Some use just repeating markup that should be moved to semi-structured content.  These may be more tedious to migrate.

## Prototype: Community Deployments Catalog

I suggest we use [Community Deployments directory](https://github.com/galaxyproject/galaxy-site/blob/master/src/Community/Deployments/index.md) (and [the entries too](https://github.com/galaxyproject/galaxy-site/tree/master/src/Community/Deployment)) to prototype our efforts.  I think this is the simplest place to start.  (And I think Events will be the hardest to port, and we should wait until last to do that.)

What I would like to see is something like what's in the old wiki:
  https://wiki.galaxyproject.org/Community/Deployments

In an ideal world the default sorting would ignore case, and users could sort by any column.  Note that this page also supports two different displays of the information.

Porting this would require 

1. moving what had been MoinMoin dl/dd/dt markup into YAML header information (look for `<div class='deploymentbox'>` in the page source), and 
2. writing a Metalsmith plugin to to render it (perhaps one already exists?).

**Comment by dannon** [comment]
See also #37

**Comment by dannon** [comment]
Almost all new content is added in this way now, structured yaml frontmatter that gets aggregated into feeds, etc.
