### ISSUE TITLE
Typos/changes in Galaxy 101

### ISSUE THREAD

**Issue by bgoas** [galaxyproject/galaxy-hub#382]
* Getting data ... (we will exons and SNPs
missing one word : use?

* Join, Subtract and Group → Join 
now has a "keep the header lines" option to leave at "No"

* cut columns from a tab
There are 2 different cut functions now, named the same. The 2nd one is to be used!

* This open a new tag within your web browser 
it should be new 'tab'

* Figure 32. ... exactly the same as in out theoretical outline shown in Fig. 27.
'out' should not be there!? replace by 'the'?

* Setting parameters "at runtime" ... What we are trying to do here is do design a generic workflow. This means that time to time 
missing 'from' at 'time to time'?

* Get back in the Analysis more 
it should be Analysis 'mode'

Thanks for that interesting tutorial, though!

**Comment by martenson** [comment]
@bgoas The file with the text of the tutorial is [here](https://github.com/galaxyproject/galaxy-hub/blob/master/src/learn/galaxy101/index.md) and anybody can easily propose changes to it directly through github. Just click 'Edit this file' icon and after you finish writing click 'start a pull request' to propose the changes. It is like a wiki!

**Comment by bgoas** [comment]
Thanks for the info! But I was actually meaning to list changes for https://galaxyproject.org/tutorials/g101/#getting-data whose bottom link brought me here, and I didn't find it here yet, as the .md file doesn't have the exact same content and almost none of the html typos (it does have the 'time to time' point)...
Any clue where that html page is? Maybe it shouldn't even point to this github...

**Comment by bgoas** [comment]
Found it at  galaxy-hub/src/tutorials/g101/index.md 
Now I also know how to search in git ;-)

**Comment by bgoas** [comment]
Should be fine now, if the pull request are accepted
