### ISSUE TITLE
NG-CHM visulaization tab is not updating

### ISSUE THREAD

**Issue by AswathyPaul** [galaxyproject/galaxy-hub#396]
As mentioned in documentation

The Galaxy visualization component does not install automatically. You will need to run the following commands in terminal mode: NOTE: The following assumes /galaxy-central is the home directory for your Galaxy instance, otherwise replace /galaxy-central with your Galaxy instance's root directory

    mv /galaxy-central/../shed_tools/toolshed.g2.bx.psu.edu/repos/md-anderson-bioinformatics/ngchm/*/ngchm/mda_heatmap_viz /galaxy-central/config/plugins/visualizations/
    cd /galaxy-central/config/plugins/visualizations/
    unzip mda_heatmap_viz.zip

Then you must restart Galaxy for the visualization portion to take effect.

    cd /galaxy-central
    sh run.sh

I have have done everything

ngs@ngs-OptiPlex-9020:~/galaxy/config/plugins/visualizations$ pwd
/home/ngs/galaxy/config/plugins/visualizations
ngs@ngs-OptiPlex-9020:~/galaxy/config/plugins/visualizations$ ls
additional_template_paths.xml  circster  csg       mda_heatmap_viz      phyloviz    scatterplot  trackster  visualization.dtd

charts                         common    graphviz  mda_heatmap_viz.zip  README.txt  sweepster    unipept

I did restart galaxy but. I am not getting the visualization option. The path is not updating in localhost either.

/home/ngs/shed_tools/toolshed.g2.bx.psu.edu/repos/md-anderson-bioinformatics/heat_map_creation/58437af2d675/heat_map_creation/heatm

what must have gone wrong ??

**Comment by tnabtaf** [comment]
@AswathyPaul: this issue tracker is for reporting problems with the web site galaxyproject.org.  To discuss Galaxy deployment issues, I recommend posting to [the galaxy-dev mailing list](https://lists.galaxyproject.org/listinfo/galaxy-dev) or the [Galaxy Gitter Channel](https://gitter.im/galaxyproject/Lobby).
