### ISSUE TITLE
broken link on gccbosc2018 page

### ISSUE THREAD

**Issue by tetron** [galaxyproject/galaxy-hub#404]
This section https://galaxyproject.org/events/gccbosc2018/venue/#housing has a link "Contact the organizers." that links to a non-existent page:

https://galaxyproject.org/events/gccbosc/organizers/

I think this link is supposed to be:

https://galaxyproject.org/events/gccbosc2018/organizers/

**Comment by martenson** [comment]
Thanks @tetron and congrats for having a fitting issue number for a missing page report
