### ISSUE TITLE
dead link for Moving data between Galaxy servers

### ISSUE THREAD

**Issue by marahhamdan** [galaxyproject/galaxy-hub#406]
I am trying to transfer data from https://ribogalaxy.ucc.ie/ to https://usegalaxy.org/ 
I found a help page for "Moving data between Galaxy servers" and it is supposed to be helpful, but the link is broken, and page cannot be found. 

The broken link:  https://galaxyproject.org/support/download-data/moving-data-between-galaxy-instances/

**Comment by dannon** [comment]
Thanks, fixed in c2e1b88feae2bcda36ff6cfa851b2b9925ecca6a.  I believe the link you're looking for is a blog entry, which points to https://genomicsvirtuallab.wordpress.com/2016/07/13/moving-data-between-galaxy-instances/
