### ISSUE TITLE
Workflow won't complete requests

### ISSUE THREAD

**Issue by jolliff** [galaxyproject/galaxy-hub#426]
Workflow says that it is successfully invoking requests, but the job won't load or appear in the histories, despite multiple attempts to run the workflow. The History pane has been refreshed multiple times and the workflow parameters have been double check (everything looks correct).

**Comment by tnabtaf** [comment]
If you are still experiencing this issue, then please create the issue in the main Galaxy repository (https://github.com/galaxyproject/galaxy)
