### ISSUE TITLE
A few broken links

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy-hub#43]
A few links are broken:

"404 Not Found":
-----------------------

* [x] https://new.galaxyproject.org/src/GalaxyProject/index.md
* [x] https://new.galaxyproject.org/src/Issues/index.md
* [x] https://new.galaxyproject.org/src/Community/index.md
* [x] https://new.galaxyproject.org/src/CloudMan/index.md
* [x] https://new.galaxyproject.org/src/Learn/index.md
* [x] https://new.galaxyproject.org/src/GalaxyOnTwitter/index.md
* [x] https://new.galaxyproject.org/src/Teach/index.md
* [x] https://new.galaxyproject.org/src/GalaxyTeam/index.md (this link instead works: https://wiki.galaxyproject.org/GalaxyTeam)
* [x] https://new.galaxyproject.org/src/DevNewsBriefs/Archive/index.md
* [x] https://new.galaxyproject.org/Admin/Internals/Implementation%20Info/
* [x] https://new.galaxyproject.org/src/Admin/index.md (this link instead works: https://new.galaxyproject.org/Community/GalaxyAdmins/)
* [x] https://new.galaxyproject.org/src/Cloud/index.md
* [x] https://new.galaxyproject.org/CloudMan/CustomizeGalaxyCloud/
* [x] https://new.galaxyproject.org/src/Develop/SourceCode/index.md
* [x] https://new.galaxyproject.org/Admin/Internals/GalaxyOps/C/
* [x] https://new.galaxyproject.org/src/Admin/Internals/GalaxyOps/Help%20Info/index.md
* [x] https://new.galaxyproject.org/Admin/Internals/GalaxyOps/Python/
* [x] https://new.galaxyproject.org/PublicGalaxyServers/PLACEHOLDER_ATTACHMENT_URL/src/Community/GalaxyAdmins/Meetups/2013_03_20/20130320Andromeda.pdf
* [x] https://globalcampus.uiowa.edu/play_recording.html?recordingId=1262344508128_1363788090133 (server not found)
* [x] https://new.galaxyproject.org/src/events/GCC2013/Abstracts/Posters/index.md#p22-andromeda-nbic-galaxy-at-surfsaras-hpc-cloud
* [x] https://www.cloud.sara.nl/ (unable to connect)
* [x] http://nbic.nl/ 
* [x] https://new.galaxyproject.org/PublicGalaxyServers/PLACEHOLDER_ATTACHMENT_URL/src/Documents/Presentations/2013DDBJWorkflow.pdf
* [x] https://new.galaxyproject.org/PublicGalaxyServers/PLACEHOLDER_ATTACHMENT_URL/src/Documents/Posters/2014ECCB_GalaxEast.pdf
* [x] http://galaxy.prabi.fr/ (unable to connect)
* [x] http://toolshed.prabi.fr/ (unable to connect)
* [x] https://genome.edu.au/wiki/GVL_Help

Placeholder errors:
--------------------------

* [x]  https://new.galaxyproject.org/ToolShed/ PLACEHOLDER_INCLUDE(/src/Ad in/Tools/LinkBox/index.md)
* [x] https://new.galaxyproject.org/support/AboutGalaxy/   - 
  - PLACEHOLDER_INCLUDE(/src/support/LinkBox/index.md)

* [x]  https://new.galaxyproject.org/CloudMan/
  - PLACEHOLDER_INCLUDE(/src/CloudMan/LinkBox/index.md)
  - PLACEHOLDER_INCLUDE(/src/CloudMan/AWS/AMIs/index.md)

* [x]  https://new.galaxyproject.org/Learn/
  - PLACEHOLDER_INCLUDE(/src/Learn/LinkBox/index.md)

* [x]  https://new.galaxyproject.org/Community/GalaxyAdmins/
  - PLACEHOLDER_INCLUDE(/src/Community/GalaxyAdmins/LinkBox/index.md)

* [x]  https://new.galaxyproject.org/Proteomics/
  - PLACEHOLDER_INCLUDE(/src/Proteomics/LinkBox/index.md)

* [x]  https://new.galaxyproject.org/IUC/
  - PLACEHOLDER_INCLUDE(/src/Admin/Tools/LinkBox/index.md)

* [x]  https://new.galaxyproject.org/Teach/GTN/
  - PLACEHOLDER_INCLUDE(/src/Teach/Header/index.md)
  - PLACEHOLDER_INCLUDE(/src/Teach/LinkBox/index.md)

* [x]  https://new.galaxyproject.org/Community/Deployments/
  * PLACEHOLDER_DICT_COLUMNS(pagename=Community/Deployment, names="Deployment, Domain, Owners, User Base, Audience", sort="Deployment", title="Hide", hide="Hide")
  * PLACEHOLDER_DICT_COLUMNS(pagename=Community/Deployment, names="Deployment, Owners, Server Topology, Compute, Memory, Storage, Disk Space, User Management", sort="Deployment", title="Hide", hide="Hide")

* [x]  https://new.galaxyproject.org/CloudMan/GettingStarted/
  * PLACEHOLDER_INCLUDE(/src/CloudMan/Header/index.md)

* [x]  https://new.galaxyproject.org/CloudMan/CapacityPlanning
  * PLACEHOLDER_INCLUDE(/src/CloudMan/Header/index.md)
  *PLACEHOLDER_INCLUDE(/src/CloudMan/LinkBox/index.md)

* [x] https://new.galaxyproject.org/Develop/
  * PLACEHOLDER_INCLUDE(/src/Develop/LinkBox/index.md)
* [x] https://new.galaxyproject.org/Admin/Tools/AddToolTutorial/
  * PLACEHOLDER_INCLUDE(/src/Admin/LinkBox/index.md)
  * PLACEHOLDER_INCLUDE(/src/Admin/Tools/LinkBox/index.md)
  * PLACEHOLDER_INCLUDE(/src/Develop/LinkBox/index.md)

* [x] https://new.galaxyproject.org/Develop/SourceCode/
  * PLACEHOLDER_INCLUDE(/src/Develop/LinkBox/index.md)
* [x] https://new.galaxyproject.org/Develop/SourceDoc/
  * PLACEHOLDER_INCLUDE(/src/Develop/LinkBox/index.md)

* [x] https://new.galaxyproject.org/Develop/
  * PLACEHOLDER_INCLUDE(/src/Develop/ResourcesAPI/index.md)
  * PLACEHOLDER_INCLUDE(/src/Develop/ResourcesTools/index.md)

* [x] https://new.galaxyproject.org/Develop/BestPractices/
  * PLACEHOLDER_INCLUDE(/src/Admin/Tools/LinkBox/index.md)
  * PLACEHOLDER_INCLUDE(/src/Develop/LinkBox/index.md)

* [x] https://new.galaxyproject.org/Develop/CSS/
  * PLACEHOLDER_INCLUDE(/src/Develop/LinkBox/index.md)

* [x] https://new.galaxyproject.org/Develop/Architecture/
  * PLACEHOLDER_INCLUDE(/src/Develop/LinkBox/index.md)

* [x] https://new.galaxyproject.org/Develop/JSA/
  * PLACEHOLDER_INCLUDE(/src/Develop/LinkBox/index.md)

* [x] https://new.galaxyproject.org/Admin/Internals/DataModel/
  * PLACEHOLDER_INCLUDE(/src/Admin/LinkBox/index.md)
  * PLACEHOLDER_INCLUDE(/src/Develop/LinkBox/index.md)

* [x]  https://new.galaxyproject.org/Admin/Internals/ApplicationLogging/
  * PLACEHOLDER_INCLUDE(/src/Develop/LinkBox/index.md)

* [x] https://new.galaxyproject.org/Admin/Internals/GalaxyOps/
 * PLACEHOLDER_INCLUDE(/src/Admin/LinkBox/index.md)
* [x] https://new.galaxyproject.org/events/GCC2013/
 * PLACEHOLDER_INCLUDE(/src/events/GCC2013/Header/index.md)
 * PLACEHOLDER_INCLUDE(/src/events/GCC2013/LinkBox/index.md)

* [x]  https://new.galaxyproject.org/events/GCC2013/Lightning/#andromeda-nbic-galaxy-at-surfsaras-hpc-cloud
  * PLACEHOLDER_INCLUDE(/src/events/GCC2013/Header/index.md)
  * PLACEHOLDER_INCLUDE(/src/events/GCC2013/LinkBox/index.md)

* [x] https://new.galaxyproject.org/Teach/Trainers/#galaxy_40_prabi_project
  * PLACEHOLDER_INCLUDE(/src/Teach/Header/index.md)
  * PLACEHOLDER_INCLUDE(/src/Teach/LinkBox/index.md)

others
---------

* [x] on this page: https://new.galaxyproject.org/support/AboutGalaxy/ is this `There are many Choices when you want to learn more about using Galaxy!` The second link is leading to the page where I'm currently on

**Comment by dannon** [comment]
I'm working on fixing the link logic at https://github.com/galaxyproject/galaxy-site/tree/fix_link_logic.

This will handle cases where ```/src``` and/or ```index.md``` are being left in published links.

**Comment by martenson** [comment]
I made sure all of these are either fixed or fixed them myself.
Missing pages added here: https://github.com/galaxyproject/galaxy-hub/issues/99

**Comment by bgruening** [comment]
Great work @martenson! And sorry for not helping.
