### ISSUE TITLE
Galaxy 18.05 mysql Too many connections

### ISSUE THREAD

**Issue by gad83** [galaxyproject/galaxy-hub#438]
Hello gents,

I just finished installing a new GALAXY 18.05 installation.
After half an hour running, mysql (version 5.1.73-8.0.1) is getting over 512 connections and hitting that limit. Nobody is connected except me.
So I increased it to 1024 and I tried database_engine_option_pool_recycle = 7200 and 300 and it still hits the max connection (=1024).
Any ideas?

Thanks,
Edgar

**Comment by martenson** [comment]
Please create the issue in the main Galaxy repository (https://github.com/galaxyproject/galaxy) as requested in https://github.com/galaxyproject/galaxy-hub/issues/437#issuecomment-421356435
