### ISSUE TITLE
NewsGraphics are missing

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy-hub#45]
Many images that are supposed to be under `/src/images/NewsGraphics` are missing.
E.g. src="/images/NewsGraphics/2016_07_GalaxyRelease_Highlights.png" alt="v16.07 Galaxy Release Highlights"

Should we get some manually?

**Comment by malloryfreeberg** [comment]
It looks like src/images/NewsGraphics is now src/images/news-graphics.

I'll take a stab at finding/updating these links

**Comment by malloryfreeberg** [comment]
@bgruening @dannon I searched galaxy-hub and didn't see any instances of /images/NewsGraphics/* left. Looks like the links are all updated to /images/news-graphics. Unless there's something else to fix, this issue can probably be closed.

**Comment by bgruening** [comment]
cool, thanks!
