### ISSUE TITLE
Move Galaxy Training Network member directory out of hub and into training material website

### ISSUE THREAD

**Issue by tnabtaf** [galaxyproject/galaxy-hub#457]
[Training Materials Issue #1055](https://github.com/galaxyproject/training-material/issues/1055) is about getting the current [GTN trainers directory](https://galaxyproject.org/teach/trainers/) into the training materials repo and out of the hub.  This issue handles the part about getting it out of the hub.

**Comment by NickSto** [comment]
Seems to be complete.
