### ISSUE TITLE
Will https://galaxyproject.org/search/getgalaxy/ stay?

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy-hub#50]
Otherwise we need to remove the links.

**Comment by dannon** [comment]
I would *like* to simplify this into a single channel search -- that is, the comprehensive search happens from the masthead search box which exists on all pages.

**Comment by tnabtaf** [comment]
The https://galaxyproject.org/search/getgalaxy/ and https://galaxyproject.org/search/usegalaxy/ are targeted at different audiences, and search a different but overlapping set of sites.  https://galaxyproject.org/search/web/ searches everything.

I'm not sure if the added value of having separate user and admin searches available is worth the added work (which is not much) and any confusions (can't measure that).

**Comment by dannon** [comment]
Yeah, my main concern was the value of relying on user-side segmentation and knowledge of what corpus they actually want to search.

So should we hook the existing /search/web up to the masthead search box for now and see how that works out, and go from there?

**Comment by bgruening** [comment]
> So should we hook the existing /search/web up to the masthead search box for now and see how that works out, and go from there?

Yes please :)

**Comment by tnabtaf** [comment]
I believe that all links within the hub have been updated to point to the new unified unified Galaxy search.  So, the usegalaxy search exists no more.

**Comment by martenson** [comment]
@tnabtaf I believe we should redirect the URLs to hub splashpage. Killing URLs is bad.

**Comment by dannon** [comment]
Those urls should just redirect to search, yeah.

**Comment by dannon** [comment]
(I'm working on seeing if I can update the url redirects now)

**Comment by dannon** [comment]
Redirects are done, search should all work.  Open new issues as necessary.
