### ISSUE TITLE
Support syntax highlighting

### ISSUE THREAD

**Issue by VJalili** [galaxyproject/galaxy-hub#507]
Is it feasible to support syntax highlighting?

**Comment by martenson** [comment]
have a look at https://github.com/galaxyproject/galaxy-hub/pull/179

**Comment by VJalili** [comment]
Thanks, so I guess it just requires adding `highlight: true` to the top of the page?!

**Comment by martenson** [comment]
```
---
highlight: true
---
```

**Comment by VJalili** [comment]
Excellent, thanks!
