### ISSUE TITLE
various masthead menu sizes

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy-hub#509]
https://galaxyproject.org/ and https://galaxyproject.org/use/ have different masthead menu sizes/fonts

**Comment by dannon** [comment]
Should be fixed in 9b217da0190c5599ff2ea617f13bda6442d656c9 and 9429802ab5cd7a0febe2b07902b24a7f3909b776.  In-page styling for the use layout was not scoped appropriately.
