### ISSUE TITLE
Only build the changed files

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy-hub#51]
If it is possible it would be super nice if the `make build` or `make serve` could only build the parts that were actually changed. This will also speed up later CI integrations.

**Comment by dannon** [comment]
I'd love to have this work, but the use of collections makes it difficult.  This is why 'make watch' is problematic as well.  Pages can include content from various sources and even if the page contents (the source index.md for the page) have not changed, the page might render differently depending on template or collection changes across the site.

**Comment by afgane** [comment]
Is your setup running just the build step with nginx serving the site faster than `make serve`?

**Comment by dannon** [comment]
@afgane Very slightly, I'd guess.  And I never have to leave a terminal open running the server :)

**Comment by dannon** [comment]
It's much, much faster to build now, so I'm closing this for the time being.  We'll want to revisit build improvements with the 'make watch', etc., down the road perhaps.
