### ISSUE TITLE
broken link to Trackster

### ISSUE THREAD

**Issue by dsiegele** [galaxyproject/galaxy-hub#546]
Starting page: https://galaxyproject.org/new-visualization-page/
.....More information about using Trackster can be found here: [Trackster](https://galaxyproject.org/Trackster/)

The link to Trackster leads to a "Page Not Found"

**Comment by tnabtaf** [comment]
Hi @dsiegele, well it took me over a year, but I got to this.  I dropped the page as it was not being maintained, and not linked to from anywhere.  Thus, the broken link was dropped with the page too.
