### ISSUE TITLE
Apply changes from finalmigrate

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy-hub#55]
https://gist.github.com/0ac78d035079fb83ce9fe9de8ccdf87a

**Comment by bgruening** [comment]
Anyone up for this challenge? Just apply this patch, test it locally and learn how things work and push it as PR.

Get in touch at https://gitter.im/galaxyproject/Lobby

**Comment by martenson** [comment]
I am afraid this patch has become obsolete due to changes merged in the meantime.

**Comment by dannon** [comment]
@martenson Yeah, it was already obsolete when I posted it, it's not going to be easy to apply.

**Comment by dannon** [comment]
I just went through this again and we've rewritten/dropped/whatever most of the content here.  Closing this, though someone else is welcome to doublecheck to make sure we didn't miss any changes.
