### ISSUE TITLE
Joiner output for metaphlann2

### ISSUE THREAD

**Issue by SumTot** [galaxyproject/galaxy-hub#596]
Hello!
I would like to do a metagenomics analysis with the "_MetaPhlAn2 to profile the composition of microbial communities_" tool from Galaxy and using as input file, one that is the output of "_FASTQ joiner on paired end reads_" tool. Because I would like to use the forward and reverse fastq sequences from the same sample at the same time.

However, I always get an error and failure when I try this. It seems to work only with the forward or the reverse fastq sequence, but no when they´re together.
Someone could help me? Is there specific parameters that I should have in mind?
Thanks!

**Comment by tnabtaf** [comment]
Hi @SumTot ,

Can you post this question to https://help.galaxyproject.org/, the project's help site.  Issues here are for reporting problems with the Galaxy Hub site (galaxyproject.org).

Thanks,
Dave C

**Comment by SumTot** [comment]
Ok,
Thanks
