### ISSUE TITLE
Broken link in NGS tutorial 

### ISSUE THREAD

**Issue by catalinaioan3** [galaxyproject/galaxy-hub#599]
There is a broken link in this page 
https://galaxyproject.org/tutorials/ngs/

In the phrase below, the link under "this page" redirects to a page that no longer exists.
> Fastq format is not strictly defined and its variations will always cause headache for you. See this page for more information. 

I'm not sure what the linked document contained, but, if my deductions are right,  I believe it should point to this new document.

SRA File Format Guide: https://www.ncbi.nlm.nih.gov/sra/docs/submitformats/

**Comment by tnabtaf** [comment]
Thank you @catalinaioan3 !  This has now been fixed and will show up on the site shortly.
