### ISSUE TITLE
Imported g101 workflow problem

### ISSUE THREAD

**Issue by remmerse** [galaxyproject/galaxy-hub#614]
I am a new GALAXY user and have been following the introductory tutorial.  Although running the individual steps works, running a workflow I created or the g101 workflow I imported results in no output data. Step 7 "Join two Datasets on data 6 and data 1" seems to be the problem. Under edit for that step the Info box states: "Error parsing command line". Is this join tool (Join, Subtract and Group/Join two Datasets side by side on a specified field) incompatible with use in a workflow?

**Comment by tnabtaf** [comment]
HI @remmerse,

This channel is for reporting problems with the GalaxyProject.org website.  For questions about training, I suggest posting your question to the Galaxy Training Network Gitter channel: https://gitter.im/Galaxy-Training-Network/Lobby
