### ISSUE TITLE
Instruction on using Hall of Fame for other projects

### ISSUE THREAD

**Issue by mubashir-rehman** [galaxyproject/galaxy-hub#641]
Kindly provide a easy to comprehend way to use the same Hall-Of-Fame (https://training.galaxyproject.org/training-material/hall-of-fame) style page for another project where contributors can themselves easily add by adding info in a _.yaml or any other form.

**Comment by tnabtaf** [comment]
Hi @mubashir-rehman,

That wasn't the hub-editors groups work.  I suggest looking at the source for the [hall of fame code](https://github.com/galaxyproject/training-material/search?q=hall+of+fame) in the training repo.  That will likely give you a place to start.

Cheers,
Dave C
