### ISSUE TITLE
MultiQC

### ISSUE THREAD

**Issue by niallghowlett** [galaxyproject/galaxy-hub#643]
Hi, I'm trying to run MultiQC on 8 fastq files and get the following output:

![Screen Shot 2020-10-18 at 21 57 43](https://user-images.githubusercontent.com/67837949/96393457-25f7f480-118d-11eb-9ead-5e35ba30c2e5.png)

**Comment by tnabtaf** [comment]
HI @niallghowlett 

This channel is for reporting problems with the GalaxyProject.org website. For problems with usegalaxy.org I suggest posting this to the Galaxy Help foum: https://help.galaxyproejct.org.
