### ISSUE TITLE
chemical-tool-box cleanup?

### ISSUE THREAD

**Issue by tnabtaf** [galaxyproject/galaxy-hub#674]
Trying to do some consolidation on the hub before migrating to a new platform. Came across the [`/src/chemical-tool-box/index.md`](https://galaxyproject.org/chemical-tool-box/) file.  This describes a GitHub repo and Toolshed metapackage.  Since that page was created, the Chemical Tool Box has also become a public server, [described in the Platform directory](https://galaxyproject.org/use/chemicaltoolbox/).  I suspect these pages should be merged into the platform directory page.

And it looks like there is also a [Docker container for this in Quay.io](https://quay.io/repository/bgruening/galaxy-chemicaltoolbox), and that in turn is used by CloudLaunch, [here](https://github.com/galaxyproject/ansible-cloudlaunch/blob/master/cloudlaunch_clouds_and_apps.json) and [here](https://github.com/galaxyproject/cloudlaunch-registry/blob/master/app-registry.yaml). If we merge these two pages, then we'll also need to update CloudLaunch as it points to [`/src/chemical-tool-box/index.md`](https://galaxyproject.org/chemical-tool-box/).

**Comment by tnabtaf** [comment]
@bgruening What do you think?  I can add a container description to the platform directory entry for the Chemical Tool Box, and submit PR's for CloudLaunch.

**Comment by bgruening** [comment]
I agree this page should be folded into the Platform directory. In regards to CloudLaunch I'm not sure this is working anymore. But if its working we actually should link all Docker containers there ... since all should work in theory.

**Comment by tnabtaf** [comment]
Thanks.  I will merge this page in the hub and submit a PR to CloudLaunch.

**Comment by tnabtaf** [comment]
And done.

* [CloudLaunch Registry](https://github.com/galaxyproject/cloudlaunch-registry/pull/26)
* [Ansible CloudLaunch](https://github.com/galaxyproject/ansible-cloudlaunch/pull/5)
