### ISSUE TITLE
 Link to get Galaxy (local) is dead

### ISSUE THREAD

**Issue by annalefarova** [galaxyproject/galaxy-hub#700]
The [link](https://galaxyproject.org/use/getgalaxy/) to "get Galaxy" from ["use" page](https://galaxyproject.org/use/) returns "page not found".
But I've managed to found the working version of this [link](https://galaxyproject.org/admin/get-galaxy/) in google.

**Comment by dannon** [comment]
Thanks!  This should be fixed in b9d0e42f47b6bf9b383057e88ee7b956c67a4a9f
