### ISSUE TITLE
What machine is orval.galaxyproject.org ?

### ISSUE THREAD

**Issue by nturaga** [galaxyproject/galaxy-hub#721]
Hi

I'm trying to understand what machine IP from galaxy is named `orval.galaxyproject.org` ? 

Can anyone tell me what machine it is? And what it is running exactly? 

I'll tag a few galaxy folks here, @natefoo and @dannon .

Best,

Nitesh

**Comment by natefoo** [comment]
Hey @nturaga!

orval is housed at Penn State and used for general large file storage where we don't want to pay data storage or egress costs on a cloud provider. For example, [depot.galaxyproject.org](https://depot.galaxyproject.org/) is served from orval. Not sure what details you're looking for here but it runs a recent version of [SmartOS](https://www.joyent.com/smartos) and the orval that is exposed to the public internet is actually a virtualized host running a [zone](https://wiki.smartos.org/how-to-create-a-zone/).

**Comment by bgruening** [comment]
It stores for example Bioconductor tarballs and since we are currently rebuilding Bioconductor packages you might see some traffic in regards to backup bioc-tarballs.

**Comment by mtmorgan** [comment]
it did show up when we were looking at egress; it probably makes sense to use `rsync` to maintain a local repository, and point to that rather than pulling from our repository; https://bioconductor.org/about/mirrors/mirror-how-to/ for some basic instructions; we are actually in the process of updating this and it might be necessary to talk with @lshep about credentials / long-term access.

**Comment by nturaga** [comment]
@natefoo and @bgruening Thanks a lot for your answers! We understand now what is going on.

**Comment by mtmorgan** [comment]
orval is downloading 50+GB daily, every day, since at least the beginning of the year (5.3 TB in the first 101 days); is this really what you intend? It doesn't really seem to be consistent with 'currently' rebuilding Bioconductor packages...

**Comment by bgruening** [comment]
No, this seems totally wrong. I will ping a few admins of this machine.

**Comment by natefoo** [comment]
cargo-port (which maintains the mirror of Bioconda packages, including Bioconductor) appears to require verifying checksums of downloaded archives but does not properly pass in the expected checksum hash of Bioconda packages. As a result, when the daily Jenkins job to update cargo-port archives runs, it fetches all the updated Bioconductor packages (and all the rest of the Bioconda packages it's missing) and refuses to store them after failing to validate the checksum. I have addressed this in galaxyproject/cargo-port#169.

**Comment by mtmorgan** [comment]
Thanks for addressing this; it seems like downloads are much reduced.

**Comment by bgruening** [comment]
Cool, thanks for checking and sorry for the mess.
