### ISSUE TITLE
better practical usage description about what you can do with Galaxy

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy-hub#745]
Discussed with  @wm75 at GCC that we should remove the following ...

![image](https://user-images.githubusercontent.com/469983/124728030-898aa380-df0f-11eb-9448-4b414825fa97.png)

And add a paragraph about what you actually can do with Galaxy:

* data analysis
* using tools
* combining tools to workflows
* running RStudio and Jupyter
* managing PB of data ...

**Comment by millen2223** [comment]
@NickSto  thank you for positive feedback!

**Comment by beatrizserrano** [comment]
I guess that we can close this issue, since the home page has been updated
