### ISSUE TITLE
Incomplete/format issues on critical wiki pages

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy-hub#76]
Found so far:

 - [x] Support is listed in the first two menus. Is this intentional? It could be removed from the first (Communicate) and be replaced with the Mailing List link (has mailing lists, irc, and biostars included, but not complete (IRC details) and links point to Support page items that do not exist right now - see below). Maybe name the menu item "Contact"? 
---
 - [x] If rename Mailing Lists to Contact, change this everywhere
---
 - https://new.galaxyproject.org/support/
  - [x] lower content on the page is missing, this is very much used for user Qs
  - [x] has old # info at top: #acl WikiAdminGroup:read,write,revert All:read
  - [x] Learn - points to old wiki
  - [x] Teach - points to old wiki
  - [x] **GalaxyProject.org** → Execute a _Custom search_ through all project content - the bold link points to the old wiki, the italic link doesn't go anywhere (but has new wiki URL)
  - [x] Q&A at Galaxy Biostars (**claim your account**) - the bold link points to the old wiki
  - [x] Galaxy Project Workshop 2015 - link points to old wiki
  - [x] Known Issues - migrate all content to new wiki
  - [x] Remove custom search boxes? and this: PLACEHOLDER_INCLUDE(/src/support/LinkBox/index.md)
  - [x] Custom searches paragraph, "The **MailingList** search finds" - bold points to old wiki
  - [x] Mailing Lists paragraph, all bullet items have new wiki URL but sections missing
  - [x] IRC Channel paragraph - header only, is where content on page ends
---
 - https://new.galaxyproject.org/Learn/ 
  - [x] complete but has this at top: PLACEHOLDER_INCLUDE(/src/Learn/LinkBox/index.md)
  - [x] TODO - check all links
---
 - https://new.galaxyproject.org/support/#mailing-lists
  - [x] Consider renaming page to "Contact" - we probably just need one comprehensive contact summary page - it can link out if there are details we want to share
  - [x] Bulleted links point to Support items that do not exist (Support needs to be restored first, or new pages created to replace the content as sub-items)
  - [x] IRC details need to be added
---
 - https://new.galaxyproject.org/Learn/ManagingDatasets/
  - Page intact
  - [ ] TODO - check all links

Hunting for more

**Comment by dannon** [comment]
@jennaj Thanks for going through the wiki.  Especially for small things like links pointing to the wrong spot, please feel free to just go ahead and make changes!

**Comment by jennaj** [comment]
@dannon Thanks! I'm going to do a round up of items, then make the edits. Today! Finally caught up on other tasks

**Comment by dannon** [comment]
@jennaj I went ahead and fixed the structural issues in the page, leaving the content edits up to you.

**Comment by martenson** [comment]
I solved most of the issues here with ef7af6299a8bc61e4d2b2848f3497b5973dfd87f 44802ce684d87b67577847f475af8a816caa3d46 df302ae86207c312f025922d7bcba01ceb509c9b 

I opened new or commented in existing for issues that are tracked elsewhere.
