### ISSUE TITLE
Rename to galaxy-hub ? (RFC)

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy-hub#79]
Now that we have a set name, and before we get too far into using this, should I rename this repository `galaxyproject/galaxy-hub`?

**Comment by bgruening** [comment]
better sooner than later ...

**Comment by dannon** [comment]
@bgruening That's what I was thinking too, I just wanted to give people a chance to yell "STOP, that's a terrible idea!" before I did it :)

**Comment by bgruening** [comment]
Anyone wants to yell? Yell now or ... :)
@dannon does it make sense to create a github group for Galaxy Hub, so we can ping everyone?

**Comment by dannon** [comment]
@bgruening We can use @galaxyproject/hubeditors, which is all vetted editors?

**Comment by bgruening** [comment]
Ok, sounds good!

**Comment by dannon** [comment]
Renamed.
