### ISSUE TITLE
Don't have a way to link to images.

### ISSUE THREAD

**Issue by tnabtaf** [galaxyproject/galaxy-hub#798]
Hi All,

Sometimes we want to show an image, all by itself in the browser.  We can show images in pages, but we are having difficulty adding links to an image.  We've tried various combinations of HTML and Markdown, and different variations with paths, but can't seem to get it to work.

For example:

```
<a href="./image.png">

![Image of a thing](image.png)

</a>
```

creates a link (and displays the image in the Markdown page), but the link does not show the image when clicked. It gets an error.  We have tried various combinations of paths (relative, absolute, local, including `content` or not) and can't find one that works.

**Comment by dannon** [comment]
@tnabtaf This works in my testing:

[![Image of a thing](/src/images/people/dannon.jpg)](/src/images/people/dannon.jpg)

**Comment by tnabtaf** [comment]
I am OK with requiring that image we ling to needs to be in the `images` hierarchy.  Just did not think to try that.

**Comment by dannon** [comment]
@tnabtaf Ahh!  I didn't even mean to figure out that was the case -- I was just saying the markdown parts.  Did you try it with an image not in the `images` hierarchy and it doesn't work?

**Comment by tnabtaf** [comment]
Yes

**Comment by dannon** [comment]
Good to know.  Maybe we can improve that down the road.

**Comment by tnabtaf** [comment]
Closing issue now that we have a solution.  We may (or may not) support linking to images outside the `images` hierarchy in the future.
