### ISSUE TITLE
Anchors a little off with new styling

### ISSUE THREAD

**Issue by tnabtaf** [galaxyproject/galaxy-hub#85]
I quite like the new styling, but I've noticed one glitch (and many improvements :-): 

When following an anchor, the text at the anchor is now hidden by the top menu.  For example, 
https://new.galaxyproject.org/news/2017_01GalaxyUpdate/

links to https://new.galaxyproject.org/GalaxyUpdates/2017_01/#galaxyadmins-screencasts but it looks like this:

![anchoroff](https://cloud.githubusercontent.com/assets/1622414/21650860/3e8f950e-d25b-11e6-89cb-e15ec7d7d6c0.png)

When it should look like this:

![anchoron](https://cloud.githubusercontent.com/assets/1622414/21650923/75a7ec26-d25b-11e6-8d75-97a3ba63f9e6.png)

Not sure what can be done.  I'm fighting the same problem on the GAMe website.

**Comment by dannon** [comment]
@tnabtaf I'll take a look now.

**Comment by dannon** [comment]
Should be fixed in ebe9f0ce
