### ISSUE TITLE
ToolBox and tool-box broken links

### ISSUE THREAD

**Issue by CCranney** [galaxyproject/galaxy-hub#881]
[The User Defined Toolbox Filters](https://galaxyproject.org/user-defined-toolbox-filters/) page has a broken link to ToolBox. This is the broken link:
https://galaxyproject.org/ToolBox/

And then the page suggests/redirects to the following link, which is also broken:
https://galaxyproject.org/tool-box/

**Comment by NickSto** [comment]
Hi, thanks for the report!

It looks like this may never have been a valid link. Seems like it was probably inserted mistakenly by an automatic [link detection pass](https://github.com/galaxyproject/galaxy-hub/commit/72fafb84523712a435f4bc5c7d34bc2e45e0e4d3) long ago that linked any CamelCased word.
