### ISSUE TITLE
The events archive page is showing all events.

### ISSUE THREAD

**Issue by tnabtaf** [galaxyproject/galaxy-hub#893]
Hi All,

The [Events Archive page](https://galaxyproject.org/events/archive/) lists all past events since we moved to Metalsmith.  Which could be great!  Except, that the [Events Page](https://galaxyproject.org/events/) says the archive only lists things more than a year old.

Some possible solutions:
1. Update the events page text to just say it lists past events (easy!)
1. Update the events archive page to list only events that are more than a year old.

I'm leaning towards solution 1.

**Comment by NickSto** [comment]
Well that's not right.

Let me check it out and see if solution 2 would actually be easy too.

**Comment by NickSto** [comment]
Yep, it was a [simple fix](896)! Simple mistake in the query filter.
