### ISSUE TITLE
Finish removing all `/src/*/index.md` links

### ISSUE THREAD

**Issue by NickSto** [galaxyproject/galaxy-hub#894]
There's still some left:
```
$ git grep -El '/src/.*/index\.md' | wc -l
50
```
A lot of them seem to include spaces, so maybe that let them escape the previous rounds of codemod?

There's even more that still just have the `/src/` prefix: mostly hyperlink hrefs and image srcs that point to images, but still plenty of hyperlinks pointing to pages:
```
$ git grep -El '/src/' | wc -l
1263
```

**Comment by dannon** [comment]
Leaving this open, but after #899 we're at 

```
[dannon@inneoin:~/work/galaxy-hub/content] git grep -El '/src/.*/index\.md' | wc -l
1
[dannon@inneoin:~/work/galaxy-hub/content] git grep -El '/src/' | wc -l
407
```

**Comment by dannon** [comment]
And after #901 we're at 27 for the second batch.
