### ISSUE TITLE
Blog Support

### ISSUE THREAD

**Issue by tnabtaf** [galaxyproject/galaxy-hub#96]
One of our stated goals when we started this move was to support other types of content, including blogging.  Blogs are analysis/opinion and differ from most of the hub content in that way.  However, they can still play a key role in helping people understand Galaxy and data-intensive research.

Does anyone want to take this on?  

I'm guessing it would involve using a standard set of YAML tags for blog pages.  In decreasing order of importance here's what I would like to see supported:

1. List recent blog posts in reverse chronological order.  I could see putting this on the blog home page (maybe /src/blogs/index.md ?), and maybe on the hub home page.
1. Support blog posts that are just a short summary of, and link to, an external blog page.
   - I don't want to require people to use this platform, but I want to aggregate everything in one easy to find place
1. List blog posts with a particular author, in reverse chronological order
   - Support more than one author per blog entry
1. Support tagging
1. List blog posts with a particular tag
1. Show a word cloud / list of blog tags along with counts for each tag.
1. Figure out if and how this integrates with or replaces the current Community Log Board, which basically aggregates external blog posts about administering Galaxy into one place.

Another option is to use BioStar for this. One of the "Post type"s it supports is "Blog."  Right now it appears we only use that for [entries from the GalaxyEvents Google Calendar](https://biostar.usegalaxy.org/local/search/page/?page=2&sort=update&limit=all%20time&q=blog).

I lean towards using the Hub over BioStar as I think the Hub is a better fit for blogging.

**Comment by dannon** [comment]
I agree w/ Hub over biostars.  Plan seems pretty good, and there's a lot of overlap in functionality with how we want all the 'feeds' (news, events, publications) to work.  Is this something we want to prioritize, or should we develop this functionality under one of those umbrellas first?

**Comment by tnabtaf** [comment]
I think events should go last because there is so much to it.

Is this a good place to start?  I dunno. Asking: @nekrut, @jxtx, @jgoecks

**Comment by jxtx** [comment]
Seems sensible for me. Metalsmith is made for this. The main thing is content. A blog without posts is sad. If we are going to commit to posting a few times a month then great.

**Comment by jgoecks** [comment]
+1 Hub over Biostars. @tnabtaf's order sounds good. I will commit to writing at least 1 blog post per month.

**Comment by tnabtaf** [comment]
And I'll have something to say between 4 and 8 times a year.  That gives us at least 16-20 posts per year.  That's enough.

**Comment by hrhotz** [comment]
I will try to add a few as well

**Comment by dannon** [comment]
Sounds great.  I can spec out a blog format this week.

**Comment by bgruening** [comment]
Is there any template so far. I would like to write to some topics. Or should I just start and we iterate over it?

**Comment by tnabtaf** [comment]
I need to learn how to set this stuff up, for this and 17 other things.  We'll also hit 5000 pubs within a month and I'd like to post that.

So, if you don't see anything here by Monday morning, ping me.

**Comment by tnabtaf** [comment]
Hi All,

Take a look at https://github.com/galaxyproject/galaxy-hub/tree/blog.  It's modeled on how events and news items are handled.  It includes two different examples.  One leads directly to an external entry, while the other one leads to a hub page (which eventually leads to an external page too, but you get the idea).

**Comment by tnabtaf** [comment]
Note that other than the metadata at the front, I'm not proposing a standard format for Blog entries.

And just noticed, that not all metadata is getting displayed on the hub page (author is missing).  I'll track that down.

**Comment by tnabtaf** [comment]
Fixed metadata display on individual blog entry pages.  Leaving this alone for awhile for others to beat up.  I will however, continue to port old entries from the community log.

**Comment by bgruening** [comment]
@tnabtaf what about place for a personal blog, that are then aggregated into a planet.galaxyproject.org blog?

**Comment by tnabtaf** [comment]
@bgruening I'm not sure I fully understand the proposal.  But here's a response anyway:

**Personal blogs:** 

I'm pretty sure we could support something like personal blogs in the hub.  For example:

- `/people/bjoern-gruening/blog/index.md` would mirror `/blog/index.md` but only have bjoern-gruening's blog entries in it.
- `/people/bjoern-gruening/blog/2017-010-denbi-plans/index.md` would contain the actual post.
- The index/list on `/blog/index.md` would incorporate everything under `/people/*/blog/` and  `/blog/*/`.  I think we could make that work.

Another option, that I don't like as much, would be to 

- place everything under `/blog/` 
- add something to the authors tag to include a point to a people entry
- support `/people/*/blog/` pages that index entries from that person under `/blog/`.

**Planet!**

I see `/blog/index.md` as being equivalent to planet.  It could automatically index every blog entry on the hub, and we would need to manually create entries for external blog entries.  There are very few blogs where I would want to pull every entry into the hub.

**Um...**

Not sure if that even addressed the questions.

**Comment by tnabtaf** [comment]
Took a [first stab](https://github.com/galaxyproject/galaxy-hub/commit/3e96552ab9a068493457f73a770edab4f4da8d7a) at personal blogs (implemented as option 1 described above).  But

- This draft doesn't actually work.  The personal blog page at `/src/people/dave-clements/blog/` actually lists everyone's personal blog entries, not just those from  `dave-clements`.
  - I don't know if metalsmith supports collections in any tractable way that aren't site wide.
- I'm not sure if it's worth it.  Do people actually want "personal" blogs on the Galaxy platform.

Anyway, I'll let this sit for a couple days, and if nothing occurs to me, I'll rollback the most recent commit.

**Comment by tnabtaf** [comment]
@bgruening I'm going to rollback (the particular approach to) personal blog support.  Unfortunately, I can't think of a useful way to make this work.

**Comment by bgruening** [comment]
@tnabtaf ok. No worries, was just an idea. Should not hold you back.

**Comment by tnabtaf** [comment]
Pull request #311 submitted.  @bgruening suggested you as a reviewer, but feel free to throw it at Dannon.

**Comment by bgruening** [comment]
@tnabtaf I thinks its a nice first iteration. I left a comment in the PR with an idea about a new layout, but I think this is good enough to collect content and give people a place to share ideas/projects.
