### ISSUE TITLE
Bunch of missing pages

### ISSUE THREAD

**Issue by scholtalbers** [galaxyproject/galaxy-hub#99]
edited, sorry @scholtalbers to hijack your issue

* [ ] src/Admin/Tools/ToolDependencies.md
* [ ] src/Admin/Training/ISMB2010%20Galaxy%20Tutorial%3A%20Running%20Your%20Own.md
* [x] src/CloudMan/CustomizeGalaxyCloud.md
* [ ] src/Community/TemplateCreole.md
* [ ] src/events/GCC2011/Sample%20Tracking%20and%20Instrument%20Integration.md
* [ ] src/events/GCC2011/Thinking%20Big%3A%20CloudMan%2C%20Grid%2C%20and%20Scalability.md
* [ ] src/events/GCC2011/Visualization%20and%20Visual%20Analytics.md
* [ ] src/events/GCC2011/Workflows%20and%20API.md
* [ ] src/Future/Job%20Failure%20When%20stderr.md
* [ ] src/Learn/Datatypes/index.md
* [ ] src/Learn/Interactive%20Poster.md
* [ ] src/Learn/OpenID%20Login.md
* [x] src/Learn/Screencasts/CurrentProtocolsBioinfo2012.md
* [ ] src/Learn/Screencasts/GR2007%20Screencasts.md
* [ ] src/Learn/Share/Share.md
* [ ] src/Learn/UCSC%20Galaxy%20Integration.md
* [ ] src/Learn/Uploading%20and%20Analyzing%20Genotype%20Data%20in%20Plink%20Format.md
* [ ] src/Learn/UserAccounts/UserAccounts.md
* [ ] src/Main/DataLibraries/Genome%20Data.md
* [ ] src/Main/DataLibraries/Microbes/A-J.md
* [ ] src/Main/DataLibraries/Microbes/K-Z.md
* [ ] src/Main/DataLibraries/Microbes.md
* [ ] src/news/GCC%20Creole.md
* [ ] https://wiki.galaxyproject.org/Future/Job%20Failure%20When%20stderr
* [x] https://new.galaxyproject.org/support/ is missing 70% of its contents (everything below IRC section) original: https://wiki.galaxyproject.org/Support
* [ ] https://wiki.galaxyproject.org/CloudMan/CustomizeGalaxyCloud/

**Comment by dannon** [comment]
Looks like this got dropped in translation by rate limiting here:  https://github.com/galaxyproject/galaxy-hub/blob/master/src/Admin/Tools/ToolDependencies.md, which is why none of the translation (shift to index.md, markdown, etc) worked.  I'm going to look for more instances of this and fix it now.

**Comment by dannon** [comment]
https://gist.github.com/3bf3dc61f8b6e341cb9b7367f1fdb9ca for a list of affected files

**Comment by martenson** [comment]
ping @jennaj this is what you are seeing with the datatypes page

**Comment by martenson** [comment]
src/admin/Interface.md is not being converted to html

**Comment by martenson** [comment]
https://wiki.galaxyproject.org/Future/Job%20Failure%20When%20stderr

**Comment by martenson** [comment]
https://new.galaxyproject.org/support/ is missing 70% of its contents (everything below IRC section)
original: https://wiki.galaxyproject.org/Support

**Comment by nsoranzo** [comment]
Another missing one: https://new.galaxyproject.org/admin/config/Eggs/ (linked from https://new.galaxyproject.org/admin/config/ , was https://wiki.galaxyproject.org/Admin/Config/Eggs )

**Comment by nsoranzo** [comment]
And https://new.galaxyproject.org/admin/data-libraries/Libraries/ (linked from https://new.galaxyproject.org/admin/data-libraries/ )

**Comment by martenson** [comment]
All sample tracking pages are missing, links reachable from [search](https://wiki.galaxyproject.org/?action=fullsearch&context=180&value=sample+tracking&titlesearch=Titles)

**Comment by bernt-matthias** [comment]
https://galaxyproject.org/ftp-upload/index.md (linked from https://galaxyproject.org/admin/config/upload-via-ftp/)

**Comment by blankenberg** [comment]
https://galaxyproject.org/admin/tools/Data%2520Tables.md linked from https://galaxyproject.org/admin/tools/data-managers/ should perhaps point to https://galaxyproject.org/admin/tools/data-tables/
